import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import {newPractice,beginPractice,advancePractice} from '../lib/politics-config.ts';
const qs=Array.from({length:205},(_,i)=>({id:String(i),number:String(i),question:'Q',options:{A:'yes',B:'no'},correct_answer:'A',source:{location:'test'}}));
test('banks contain 700 individually identified questions and valid marked answers',()=>{for(const [name,n] of [['command',500],['public',200]]){const b=JSON.parse(fs.readFileSync(new URL(`../lib/banks/politics-${name}-2026.json`,import.meta.url)));assert.equal(b.questions.length,n);assert.equal(new Set(b.questions.map(q=>q.id)).size,n);for(const q of b.questions){assert.ok(q.question);assert.ok(q.options[q.correct_answer]);assert.ok(q.source.location);assert.ok(Object.keys(q.options).length>=2);}}});
test('100 unseen +100 unseen +5, then wrong only until mastered',()=>{let s=newPractice(qs.map(q=>q.id)),seen=new Set();for(const size of [100,100,5]){s=beginPractice(s);assert.equal(s.round.ids.length,size);for(const id of s.round.ids){assert.ok(!seen.has(id));seen.add(id);}while(s.round.status==='active'){s=advancePractice(s,qs,s.round.deadline-1000,s.round.index===0?'B':'A');}}assert.equal(s.completed,205);assert.equal(s.remaining.length,0);assert.equal(s.wrong.length,3);s=beginPractice(s);assert.equal(s.round.review,true);assert.equal(s.round.ids.length,3);while(s.round.status==='active')s=advancePractice(s,qs,s.round.deadline-1000,'A');assert.equal(s.wrong.length,0);assert.equal(s.completed,205);});
test('ten missed deadlines abort; reload catches up; restart preserves round and prior progress',()=>{let s=beginPractice(newPractice(qs.map(q=>q.id)));while(s.round.status==='active')s=advancePractice(s,qs,s.round.deadline-100,'A');s=beginPractice(s);const ids=[...s.round.ids].sort();s=advancePractice(JSON.parse(JSON.stringify(s)),qs,s.round.deadline+9*120000);assert.equal(s.round.status,'aborted');assert.equal(s.completed,100);s=beginPractice(s);assert.deepEqual([...s.round.ids].sort(),ids);assert.equal(s.round.timeouts,0);s=advancePractice(s,qs,s.round.deadline+120000);assert.equal(s.round.index,2);s=advancePractice(s,qs,s.round.deadline-1,'A');assert.equal(s.round.timeouts,0);});
test('answer arriving after expiry is not applied to next question; finish committed once',()=>{let s=beginPractice(newPractice(qs.slice(0,2).map(q=>q.id)));s=advancePractice(s,qs,s.round.deadline,'A');assert.equal(s.round.index,1);assert.equal(Object.keys(s.round.answers).length,0);s=advancePractice(s,qs,s.round.deadline-1,'A');assert.equal(s.completed,2);s=advancePractice(s,qs,s.round.deadline+1000);assert.equal(s.completed,2);assert.equal(s.wrong.length,1);});

test('20/50/100 packages share unseen progress and keep aborted round intact',()=>{let s=newPractice(qs.map(q=>q.id));const seen=new Set();for(const n of [20,50,100,35]){s=beginPractice(s,n);assert.equal(s.round.ids.length,n);for(const id of s.round.ids){assert.ok(!seen.has(id));seen.add(id);}while(s.round.status==='active')s=advancePractice(s,qs,s.round.deadline-100,'A');}assert.equal(s.completed,205);s=beginPractice(newPractice(qs.map(q=>q.id)),50);s=advancePractice(s,qs,s.round.deadline+9*120000);const ids=[...s.round.ids].sort();s=beginPractice(s,20);assert.deepEqual([...s.round.ids].sort(),ids);assert.equal(s.round.ids.length,50);});
