'use client';
import Icon from '../components/Icon';
import {topics} from '../lib/content';
import Link from 'next/link';
import Leaderboard from '../components/Leaderboard';
import {mockPackages} from '../lib/mock';
export default function HomePage(){
 return <>
 <a className="skip" href="#content">Đến nội dung học tập</a>
 <header className="topbar"><div className="headerInner"><a className="brand" href="#home" aria-label="Văn phòng – Trang chủ"><img src="/logo-snp.png" alt="Logo SNP – Saigon Newport" width="54" height="58"/><div><strong>TỔNG CÔNG TY TÂN CẢNG SÀI GÒN - BINH ĐOÀN 20</strong><span>VĂN PHÒNG</span></div></a><nav aria-label="Điều hướng chính"><a className="active" href="#home">Trang chủ</a><a href="#about">Giới thiệu</a><a href="#guide">Hướng dẫn</a><a className="navCta" href="#content">Vào học tập <span aria-hidden="true">→</span></a></nav></div></header>
 <main id="home"><section className="hero" aria-labelledby="hero-title"><div className="heroShade"/><div className="heroContent"><img src="/logo-snp.png" alt="" width="78" height="85" className="heroLogo"/><p className="eyebrow">TRI THỨC VỮNG VÀNG · SẴN SÀNG NHIỆM VỤ</p><h1 id="hero-title">HỆ THỐNG ÔN TẬP –<br/>KIỂM TRA KIẾN THỨC</h1><h2>VĂN PHÒNG</h2><p className="heroTagline">Nâng cao nhận thức – Củng cố kiến thức –<br className="mobileBreak"/> Hoàn thành tốt nhiệm vụ</p></div><div className="values"><span>ĐOÀN KẾT</span><span>KỶ CƯƠNG</span><span>CHỦ ĐỘNG</span><span>SÁNG TẠO</span><span>HIỆU QUẢ</span></div><div className="flagCaption">Vững vàng vươn xa</div></section>
 <div className="shell"><div className="welcome"><span><i/> Không gian học tập của Văn phòng</span><span className="demoBadge">Ôn tập và Thi thử · TEST</span></div>
 <section id="content" className="learning"><div className="sectionHeading"><div><p className="eyebrow">HỌC TẬP MỖI NGÀY</p><h2>Chọn nội dung học tập</h2><p>Lựa chọn chuyên đề để củng cố kiến thức và chuẩn bị cho các kỳ kiểm tra.</p></div><span className="topicTotal">03 <small>CHUYÊN ĐỀ</small></span></div><div className="topicGrid">{topics.map((t,i)=><article className={`topicCard ${t.tone}`} key={t.key}><div className="topicTop"><div className="topicIcon" aria-hidden="true"><img src={t.key === 'military' ? '/topic-military-corrected.png' : `/topic-${t.key}.png`} alt="" width="160" height="160"/></div><span className="topicNumber">0{i+1}</span><h3>{t.title}</h3><p>{t.desc}</p></div><div className="topicBottom"><div className="topicMeta"><span>{t.count>0?<><b>{t.count}</b> câu hỏi TEST</>:'Chưa có câu hỏi'}</span><small>{t.count>0?'Chưa dùng chính thức':'Đang chuẩn bị'}</small></div><div className="topicActions">{t.count>0?<Link className="outlineBtn" href="/on-tap">Ôn tập</Link>:<button className="outlineBtn" disabled>Ôn tập</button>}{t.count>0?<Link className="solidBtn" href="/thi-thu">Thi thử →</Link>:<button className="solidBtn" disabled>Thi thử</button>}</div><p className="topicStatus">{t.count>0?'Ôn tập không xếp hạng. Thi thử xếp hạng gói lớn nhất.':'Chuyên đề sẽ mở khi có ngân hàng câu hỏi.'}</p></div></article>)}</div></section>
 <Leaderboard/>
 <section className="stats" aria-label="Tình trạng nội dung"><div><b>{topics.filter(t=>t.count>0).length}</b><span>Chuyên đề có câu hỏi</span></div><div><b>{topics.reduce((sum,t)=>sum+t.count,0)}</b><span>Câu hỏi TEST</span></div><div><b>0</b><span>Câu hỏi chuẩn đã phát hành</span></div><div><b>{mockPackages.filter(p=>p.enabled).length}</b><span>Gói Thi thử đã cấu hình</span></div></section>
 <section className="modeGuide" aria-label="Hướng dẫn các chức năng"><h2>Chọn chế độ phù hợp</h2><div><article><h3>Ôn tập · Học và củng cố kiến thức</h3><p>Chọn số câu, trả lời và kiểm tra đáp án ngay từng câu. Không giới hạn thời gian, không cần nhập tên và không tính xếp hạng.</p></article><article><h3>Thi thử · Cùng thi đua, cùng tiến bộ</h3><p className="encouragement">Cùng thi đua học tập, vững kiến thức, tốt nhiệm vụ.</p><p>Thử sức để tự đánh giá kiến thức, rèn luyện sự tự tin và chinh phục kết quả tốt hơn. Tham gia gói Thi thử được tính xếp hạng để cùng đồng đội thi đua trên bảng thành tích của chuyên đề.</p><p className="sessionNote">Làm bài có thời gian, chỉ xem đáp án sau khi hoàn tất. Chỉ gói lớn nhất đang mở của mỗi chuyên đề được tính xếp hạng.</p></article></div></section><section className="infoGrid"><article id="about"><p className="eyebrow">VỀ HỆ THỐNG</p><h2>Vững kiến thức.<br/>Tốt nhiệm vụ.</h2><p>Không gian ôn tập dành cho cán bộ, nhân viên Văn phòng, hỗ trợ học tập chủ động và củng cố kiến thức chính trị, pháp luật, quân sự – quốc phòng.</p><p className="infoNote">Hiện có bộ câu hỏi TEST để Ôn tập và Thi thử. Nội dung chưa được thẩm định để dùng chính thức. Ôn tập không tính thành tích; Thi thử có bảng TEST riêng cho gói lớn nhất.</p></article><article id="guide"><p className="eyebrow">HƯỚNG DẪN</p><h2>Bắt đầu thật đơn giản</h2><ol><li><span>01</span><div><h3>Chọn chuyên đề</h3><p>Tìm nội dung phù hợp với nhu cầu học tập.</p></div></li><li><span>02</span><div><h3>Chọn số câu và ôn tập</h3><p>Chọn số câu phù hợp, trả lời và đọc giải thích.</p></div></li><li><span>03</span><div><h3>Theo dõi sự tiến bộ</h3><p>Xem câu đúng, sai, chưa trả lời và ôn lại các câu cần củng cố.</p></div></li></ol></article></section></div></main>
 <footer><div className="shell footerInner"><div><strong>TỔNG CÔNG TY TÂN CẢNG SÀI GÒN - BINH ĐOÀN 20</strong><p>VĂN PHÒNG</p><small>Hệ thống ôn tập – kiểm tra kiến thức</small></div><span>Đoàn kết · Kỷ cương · Chủ động · Sáng tạo · Hiệu quả</span></div></footer>

 </>;
}

