'use client';
import DeferredHome from '../components/DeferredHome';
import StudyCounts from '../components/StudyCounts';
import Icon from '../components/Icon';

import {topics} from '../lib/content';
import Link from 'next/link';

import {mockPackages} from '../lib/mock';
export default function HomePage(){
 return <>
 <a className="skip" href="#content">Đến nội dung học tập</a>
 <header className="topbar"><div className="headerInner"><a className="brand" href="#home" aria-label="Văn phòng – Trang chủ"><img src="/logo-snp.webp" alt="Logo SNP – Saigon Newport" width="54" height="58"/><div><strong>TỔNG CÔNG TY TÂN CẢNG SÀI GÒN - BINH ĐOÀN 20</strong><span>VĂN PHÒNG</span></div></a><nav aria-label="Điều hướng chính"><Link className="partyLoginButton" href="/dang-nhap"><span>Đăng nhập đảng viên</span></Link><a className="partyLoginButton studyButton" href="#content"><span>Học tập tài liệu</span></a><Link className="partyLoginButton scheduleButton" href="/thi-dua-khen-thuong"><span>Thi đua - Khen thưởng</span></Link><Link className="partyLoginButton communityButton" href="/to-chuc-quan-chung"><span>Tổ chức quần chúng</span></Link></nav></div></header>
 <main id="home"><section className="hero" aria-labelledby="hero-title"><div className="heroShade"/><div className="heroContent"><p className="eyebrow">TRI THỨC VỮNG VÀNG · SẴN SÀNG NHIỆM VỤ</p><h1 id="hero-title">HỆ THỐNG ÔN TẬP<br/>KIỂM TRA KIẾN THỨC</h1><h2>VĂN PHÒNG</h2><p className="heroTagline">Nâng cao nhận thức – Củng cố kiến thức –<br className="mobileBreak"/> Hoàn thành tốt nhiệm vụ</p></div><div className="heroHonors"><img src="/honors-2004-2023.webp" alt="Hai biểu tượng huân chương với các mốc 2004 và 2023" width="186" height="127"/></div><div className="values"><span>ĐOÀN KẾT</span><span>KỶ CƯƠNG</span><span>CHỦ ĐỘNG</span><span>SÁNG TẠO</span><span>HIỆU QUẢ</span></div><div className="flagCaption">Vững vàng vươn xa</div></section>
 <div className="shell"><div className="welcome"><span><i/> Không gian học tập của Văn phòng</span><span className="demoBadge">Ôn tập và Thi thử · TEST</span></div>
 <section id="content" className="learning"><div className="sectionHeading"><div><p className="eyebrow">HỌC TẬP MỖI NGÀY</p><h2>Chọn nội dung học tập</h2><p>Lựa chọn chuyên đề để củng cố kiến thức và chuẩn bị cho các kỳ kiểm tra.</p></div><span className="topicTotal">{String(topics.length).padStart(2,'0')} <small>CHUYÊN ĐỀ</small></span></div><div className="quoteGreenRow"><div className="learningVoices" aria-label="Thông điệp học tập"><figure className="learningVoice"><div className="voicePortrait"><img loading="lazy" decoding="async" src="/bac-ho-hoc-tap.jpg" alt="Chủ tịch Hồ Chí Minh đọc và viết bên bàn làm việc" width="400" height="241"/></div><figcaption><blockquote>“Học để làm việc, làm người, làm cán bộ.”</blockquote><p>— Chủ tịch Hồ Chí Minh</p></figcaption></figure><figure className="learningVoice"><div className="voicePortrait"><img loading="lazy" decoding="async" src="/lenin-hoc-tap.webp" alt="V. I. Lênin" width="313" height="417"/></div><figcaption><blockquote>“Học, học nữa, học mãi.”</blockquote><p>— V. I. Lênin</p></figcaption></figure><figure className="learningVoice voiceToLam"><div className="voicePortrait"><img loading="lazy" decoding="async" src="/to-lam-hoc-tap.webp" alt="Tổng Bí thư Tô Lâm" width="648" height="289"/></div><figcaption><blockquote><p>“Học tập suốt đời trở thành một quy luật sống</p><p>Học tập suốt đời làm giàu trí tuệ, hoàn thiện nhân cách, định vị bản thân</p><p>Học tập suốt đời là chìa khóa quan trọng để nâng cao dân trí và đào tạo nhân lực”</p></blockquote><p>— Tổng Bí thư Tô Lâm</p></figcaption></figure></div><DeferredHome kind="green"/></div><div className="topicGrid">{topics.map((t,i)=><article className={`topicCard ${t.tone}`} key={t.key}><div className="topicTop"><div className="topicIcon" aria-hidden="true"><img loading="lazy" decoding="async" src={t.key === 'military' ? '/topic-military-corrected.webp' : `/topic-${t.key}.webp`} alt="" width="160" height="160"/></div><span className="topicNumber">0{i+1}</span><h3>{t.title}</h3><p>{t.desc}</p></div><div className="topicBottom"><div className="topicMeta"><span>{t.count>0?<><b>{t.count}</b> câu hỏi TEST</>:'Chưa có câu hỏi'}</span><small>{t.count>0?'Chưa dùng chính thức':'Đang chuẩn bị'}</small></div><div className="topicActions">{t.count>0?<Link className="outlineBtn" href="/on-tap">Ôn tập</Link>:<button className="outlineBtn" disabled>Ôn tập</button>}{t.count>0?<Link className="solidBtn" href="/thi-thu">Thi thử →</Link>:<button className="solidBtn" disabled>Thi thử</button>}</div><StudyCounts topic={t.key}/><p className="topicStatus">{t.count>0?'Ôn tập không xếp hạng. Thi thử xếp hạng gói lớn nhất.':'Chuyên đề sẽ mở khi có ngân hàng câu hỏi.'}</p></div></article>)}</div></section>
 <DeferredHome kind="portal"/><DeferredHome kind="ranking"/>
 <section className="stats" aria-label="Tình trạng nội dung"><div><b>{topics.filter(t=>t.count>0).length}</b><span>Chuyên đề có câu hỏi</span></div><div><b>{topics.reduce((sum,t)=>sum+t.count,0)}</b><span>Câu hỏi TEST</span></div><div><b>0</b><span>Câu hỏi chuẩn đã phát hành</span></div><div><b>{mockPackages.filter(p=>p.enabled).length}</b><span>Gói Thi thử đã cấu hình</span></div></section>
 <section className="infoGrid compactInfo"><article id="about"><p className="eyebrow">GIỚI THIỆU</p><h2>Không gian học tập Văn phòng</h2><p>Tra cứu tài liệu, học nghị quyết và củng cố kiến thức phục vụ nhiệm vụ.</p><p className="infoNote">Câu hỏi Ôn tập và Thi thử hiện là bản TEST, chưa dùng chính thức.</p></article><article id="guide"><p className="eyebrow">HƯỚNG DẪN NHANH</p><h2>Bắt đầu học tập</h2><details><summary>Học nghị quyết</summary><p>Đăng nhập → chọn đợt → đọc tài liệu → xác nhận khi đến cuối tài liệu.</p><Link href="/hoc-tap">Vào học tập →</Link></details><details><summary>Ôn tập và thi thử</summary><p>Ôn tập cho kiểm tra từng câu. Thi thử tính giờ, xem đáp án khi nộp bài. Đăng nhập trước khi bắt đầu và chọn gói lớn nhất để được xếp hạng.</p></details><details><summary>Bảo mật và bảo vệ thông tin</summary><p>Website vận hành trên Vercel, sử dụng Supabase Auth để xác thực tài khoản và Cloudflare R2 để lưu các PDF đã chuyển đổi hoặc tải mới sau khi cập nhật. Các lớp bảo vệ được kết hợp từ kết nối, đăng nhập đến quyền truy cập tài liệu.</p><p><strong>Kết nối mã hóa HTTPS:</strong> Dữ liệu trao đổi giữa trình duyệt và website được mã hóa khi truyền qua mạng, giúp hạn chế việc đọc trộm thông tin trên đường truyền.</p><p><strong>Xác thực và phiên đăng nhập:</strong> Supabase Auth kiểm tra thông tin đăng nhập. Phiên được lưu bằng cookie HttpOnly, có thời hạn và được gửi qua kết nối HTTPS trên website chính thức; mã JavaScript trong trang không thể đọc trực tiếp cookie này. Giao diện quản trị không hiển thị lại mật khẩu đã cấp.</p><p><strong>Phân quyền tại máy chủ:</strong> Hệ thống kiểm tra tài khoản và quyền được giao trước khi cho đọc tài liệu học nghị quyết hoặc thực hiện thao tác quản trị. Việc ẩn nút trên giao diện không thay thế bước kiểm tra quyền này.</p><p><strong>Bảo vệ PDF:</strong> Tài liệu trên R2 được truy cập qua liên kết có chữ ký và thời hạn, do máy chủ cấp sau khi kiểm tra quyền. Tài liệu cũ chưa chuyển vẫn dùng liên kết tạm thời từ Supabase. Không chia sẻ liên kết đọc vì người có liên kết có thể sử dụng trong thời gian còn hiệu lực.</p><p><strong>Phạm vi thông tin hiển thị:</strong> Tên, tên tài khoản trong danh sách tra cứu; ảnh đại diện, thông tin hoạt động và kết quả ở các mục công khai có thể được người truy cập xem. Quyền đọc PDF không đồng nghĩa mọi thông tin trên website đều là riêng tư.</p><p className="infoNote">Cùng bảo vệ tài khoản: không chia sẻ mật khẩu, đăng xuất khi dùng máy chung và liên hệ quản trị viên khi có dấu hiệu bất thường. Chỉ đăng tải nội dung được phép phổ biến; không đưa thông tin, tài liệu mật lên hệ thống.</p></details></article></section></div></main>
 <footer><div className="shell footerInner"><div><strong>TỔNG CÔNG TY TÂN CẢNG SÀI GÒN - BINH ĐOÀN 20</strong><p>VĂN PHÒNG</p><small>Hệ thống ôn tập – kiểm tra kiến thức</small></div><span>Đoàn kết · Kỷ cương · Chủ động · Sáng tạo · Hiệu quả</span></div><div className="authorCredit">Tác giả: <strong>Nguyễn Thanh Bình</strong> — Nhân viên Ban Kế hoạch tổng hợp</div></footer>

 </>;
}

