'use client';
import Link from 'next/link';
import AwardsExport from './AwardsExport';
import type {Campaign} from '../lib/commendations';
import {useRef,useState} from 'react';
import s from './AwardsTimelineDemo.module.css';
const milestones=[
 {month:'01',day:'10',kind:'PHÁT ĐỘNG',title:'Khởi đầu năm mới',subtitle:'Phát động phong trào thi đua',heading:'Phát động phong trào thi đua thực hiện nhiệm vụ năm',body:'Tập trung xây dựng tinh thần chủ động, trách nhiệm và phối hợp trong thực hiện nhiệm vụ của Văn phòng. Mỗi tập thể, cá nhân xác định nội dung đăng ký thi đua gắn với công việc được giao.',items:['Đăng ký mục tiêu, nội dung và chỉ tiêu thi đua của từng bộ phận.','Đề cao chất lượng tham mưu, tiến độ xử lý và trách nhiệm phối hợp.','Theo dõi kết quả để kịp thời biểu dương những cách làm hiệu quả.']},
 {month:'04',day:'20',kind:'CAO ĐIỂM',title:'Đoàn kết, lập công',subtitle:'Đợt thi đua cao điểm',heading:'Đợt thi đua cao điểm: Đoàn kết, trách nhiệm, hoàn thành tốt nhiệm vụ',body:'Gắn hoạt động thi đua với các nhiệm vụ trọng tâm; khuyến khích đề xuất sáng kiến, cải tiến phương pháp làm việc và nâng cao chất lượng phục vụ.',items:['Rà soát nhiệm vụ trọng tâm và phân công trách nhiệm cụ thể.','Chia sẻ sáng kiến có khả năng áp dụng trong công việc.','Ghi nhận kết quả thực hiện trong từng giai đoạn của đợt thi đua.']},
 {month:'06',day:'25',kind:'SƠ KẾT',title:'Nhìn lại để tiến bước',subtitle:'Sơ kết thi đua 6 tháng',heading:'Sơ kết phong trào thi đua, khen thưởng 6 tháng đầu năm',body:'Đánh giá kết quả triển khai các nội dung thi đua, nhận diện những mặt còn hạn chế và thống nhất nhiệm vụ, giải pháp trong thời gian tiếp theo.',items:['Tổng hợp kết quả thực hiện theo các nội dung đã đăng ký.','Giới thiệu cách làm hay và kinh nghiệm của các bộ phận.','Điều chỉnh giải pháp để thực hiện tốt nhiệm vụ 6 tháng cuối năm.']},
 {month:'09',day:'15',kind:'ĐIỂN HÌNH',title:'Lan tỏa điều tốt đẹp',subtitle:'Giới thiệu điển hình tiêu biểu',heading:'Biểu dương và lan tỏa các điển hình trong phong trào thi đua',body:'Giới thiệu những tập thể, cá nhân có cách làm sáng tạo và tinh thần trách nhiệm trong công tác. Nội dung công bố chính thức sẽ căn cứ hồ sơ, kết quả và quyết định được phê duyệt.',items:['Giới thiệu những đóng góp và phương pháp làm việc tiêu biểu.','Chia sẻ kinh nghiệm để các bộ phận học tập, vận dụng.','Cập nhật hình ảnh, nội dung biểu dương và văn bản liên quan.']},
 {month:'12',day:'20',kind:'TỔNG KẾT',title:'Ghi nhận và tiếp nối',subtitle:'Tổng kết, khen thưởng cuối năm',heading:'Tổng kết công tác thi đua, khen thưởng năm',body:'Nhìn lại quá trình phấn đấu trong năm, ghi nhận đóng góp của các tập thể, cá nhân và xác định phương hướng cho phong trào thi đua năm tiếp theo.',items:['Đánh giá toàn diện kết quả phong trào thi đua trong năm.','Công bố thông tin khen thưởng theo quyết định được phê duyệt.','Xác định phương hướng, nhiệm vụ và nội dung thi đua năm sau.']}
];
const years=[2026,2025,2024];
const demoEvents:Campaign[]=years.flatMap(year=>milestones.map((m,i)=>({id:`demo-${year}-${i}`,title:m.heading,date:`${year}-${m.month}-${m.day}`,description:m.body,images:[],published:true,collectives:i>=2?[{name:'Tập thể minh họa',award:'Giấy khen (minh họa)',photo:''}]:[],honorees:i>=2?[{name:'Cá nhân minh họa',position:'',award:'Bằng khen (minh họa)',photo:''}]:[]})));
export default function AwardsTimelineDemo(){
 const [year,setYear]=useState(2026),[active,setActive]=useState(0);const tabs=useRef<(HTMLButtonElement|null)[]>([]),rail=useRef<HTMLDivElement>(null);const event=milestones[active];
 function select(i:number,focus=false){setActive(i);if(focus){tabs.current[i]?.focus();tabs.current[i]?.scrollIntoView({block:'nearest',inline:'nearest',behavior:'auto'});}}
 return <main className={s.page}>
 <nav className={s.nav}><Link href="/">← Trang chủ</Link><span>Bản xem trước · Dữ liệu minh họa</span><Link href="/thi-dua-khen-thuong">Giao diện hiện tại ↗</Link></nav>
 <header className={s.hero}><div className={s.heroInner}><div className={s.eyebrow}>VĂN PHÒNG TỔNG CÔNG TY</div><h1>Thi đua <i>&</i> Khen thưởng</h1><p>Mỗi dấu mốc, một hành trình phấn đấu.</p><div className={s.motto}>ĐOÀN KẾT <span>·</span> TRÁCH NHIỆM <span>·</span> SÁNG TẠO <span>·</span> HIỆU QUẢ</div></div><div className={s.heroMark} aria-hidden="true">★<small>HÀNH TRÌNH<br/>CỐNG HIẾN</small></div></header>
 <div className={s.workspace}>
 <aside className={s.years} aria-label="Chọn năm"><span>NĂM</span>{years.map(y=><button key={y} aria-pressed={year===y} onClick={()=>{setYear(y);setActive(0);rail.current?.scrollTo({left:0,behavior:'auto'});}}>{y}<small>05 dấu mốc</small></button>)}<div className={s.yearLine}/></aside>
 <section className={s.mainContent}>
 <div className={s.sectionHeading}><div><span className={s.kicker}>DÒNG THỜI GIAN</span><h2>Hành trình thi đua <em>{year}</em></h2></div><p>Chọn một dấu mốc<br/>để xem nội dung đầy đủ</p></div>
 <AwardsExport key={year} year={year} demoEvents={demoEvents}/><div className={s.timelineShell}><div className={s.scrollHint}>← Vuốt ngang để xem các dấu mốc →</div><div ref={rail} className={s.rail}><div className={s.timeline} role="tablist" aria-label={'Dấu mốc thi đua năm '+year}><div className={s.axis} aria-hidden="true"><span>THÁNG 01</span><span>THÁNG 12 →</span></div>{milestones.map((m,i)=><div key={m.month} className={`${s.bone} ${i%2?s.below:s.above} ${active===i?s.chosen:''}`}><span className={s.dot} aria-hidden="true"/><button ref={el=>{tabs.current[i]=el;}} id={'milestone-'+i} role="tab" aria-selected={active===i} aria-controls="milestone-content" tabIndex={active===i?0:-1} onClick={()=>select(i)} onKeyDown={e=>{let n:number|undefined;if(e.key==='ArrowRight')n=(i+1)%milestones.length;if(e.key==='ArrowLeft')n=(i+milestones.length-1)%milestones.length;if(e.key==='Home')n=0;if(e.key==='End')n=milestones.length-1;if(n!==undefined){e.preventDefault();select(n,true);}}}><span className={s.tabDate}>{m.day}.{m.month}<small>{m.kind}</small></span><b>{m.title}</b><span className={s.tabSubtitle}>{m.subtitle}</span><span className={s.tabArrow} aria-hidden="true">{active===i?'−':'↗'}</span></button></div>)}</div></div></div>
 <article id="milestone-content" role="tabpanel" aria-labelledby={'milestone-'+active} className={s.detail} key={year+'-'+active} tabIndex={0}>
 <div className={s.detailTop}><span>{event.kind} <i/> {event.day}/{event.month}/{year}</span><span>Mẫu nội dung · {String(active+1).padStart(2,'0')} / 05</span></div>
 <div className={s.detailGrid}><div><h3>{event.heading} {active===0||active===4?year:''}</h3><p className={s.body}>{event.body}</p><h4>Nội dung triển khai</h4><ol className={s.items}>{event.items.map((item,i)=><li key={item}><span>{String(i+1).padStart(2,'0')}</span><p>{item}</p></li>)}</ol></div><aside className={s.summary}><span className={s.summaryIcon} aria-hidden="true">✦</span><span className={s.kicker}>GHI NHẬN & LAN TỎA</span><h4>Thành tích được trân trọng.<br/>Nỗ lực được tiếp nối.</h4><p>Khi đưa vào sử dụng, mục này hiển thị tập thể, cá nhân được khen thưởng cùng hình ảnh và quyết định tương ứng.</p><div className={s.sampleTag}>Chưa kết nối dữ liệu thực tế</div></aside></div>
 <footer className={s.detailFooter}><span>Đang xem: {event.subtitle}</span><button onClick={()=>select((active+1)%milestones.length)}>Dấu mốc tiếp theo →</button></footer>
 </article>
 <p className={s.demoNote}>Bản demo bố cục: các năm, thời điểm và nội dung trên chỉ để minh họa. Chọn mục mới sẽ ẩn nội dung mục trước.</p>
 </section></div></main>;
}
