'use client';
import Link from 'next/link';
import {useEffect,useRef,useState} from 'react';
const groups=[{id:'union',name:'Công đoàn Bộ phận Văn phòng',short:'Công đoàn'},{id:'women',name:'Hội Phụ nữ Văn phòng',short:'Hội Phụ nữ'},{id:'youth',name:'Đoàn thanh niên Văn phòng',short:'Đoàn thanh niên'}];
type Person={id:string;name:string;position?:string;active?:boolean};
type Activity={author_name?:string;created_at?:string;id:string;org:string;title:string;occurred_on:string;content:string;image:string;updated_at:string;members:Person[]};
type Rank={person_id:string;name:string;position:string;photo:string;total:number;union_count:number;women_count:number;youth_count:number;rank:number};
type Data={me:{id:string;name:string;role:string}|null;org:string;tabs:{org:string;count:number;latest:string}[];events:Activity[];page:number;pages:number;total:number;year:number;years:number[];ranking:Rank[];rankPage:number;rankPages:number;rankTotal:number;imageBase:string;avatarBase:string};
type Draft={id?:string;version?:string;org:string;title:string;date:string;content:string;image:string;members:string[]};
const dateLabel=(s:string)=>s.split('-').reverse().join('/');
async function request(body:unknown){const r=await fetch('/api/to-chuc-quan-chung',{method:'POST',headers:body instanceof FormData?undefined:{'Content-Type':'application/json'},body:body instanceof FormData?body:JSON.stringify(body)});const d=await r.json();if(!r.ok)throw Error(d.error||'Chưa lưu được dữ liệu.');return d;}
async function compress(file:File){if(file.size>=10*1024*1024||!['image/jpeg','image/png','image/webp'].includes(file.type))throw Error('Chọn JPG, PNG hoặc WebP nhỏ hơn 10 MB.');const bitmap=await createImageBitmap(file);try{const scale=Math.min(1,1200/Math.max(bitmap.width,bitmap.height));const canvas=document.createElement('canvas');canvas.width=Math.max(1,Math.round(bitmap.width*scale));canvas.height=Math.max(1,Math.round(bitmap.height*scale));canvas.getContext('2d')!.drawImage(bitmap,0,0,canvas.width,canvas.height);const blob=await new Promise<Blob>((resolve,reject)=>canvas.toBlob(b=>b?resolve(b):reject(Error('Không xử lý được ảnh.')),'image/webp',.78));if(blob.size>1048576)throw Error('Ảnh còn lớn sau khi nén, vui lòng chọn ảnh khác.');return blob;}finally{bitmap.close();}}
export default function CommunityActivities(){
 const [detail,setDetail]=useState<Activity|null>(null);
 const [data,setData]=useState<Data|null>(null),[org,setOrg]=useState(''),[page,setPage]=useState(1),[year,setYear]=useState(new Date().getFullYear()),[rankPage,setRankPage]=useState(1),[reload,setReload]=useState(0),[loading,setLoading]=useState(true),[error,setError]=useState(''),[notice,setNotice]=useState('');
 const [draft,setDraft]=useState<Draft|null>(null),[people,setPeople]=useState<Person[]>([]),[query,setQuery]=useState(''),[busy,setBusy]=useState(false),[editorLoading,setEditorLoading]=useState(false),[editorError,setEditorError]=useState(''),[photo,setPhoto]=useState<Blob|null>(null),[preview,setPreview]=useState('');
 const editor=useRef<HTMLFormElement>(null),selection=useRef<HTMLInputElement>(null),tabs=useRef<(HTMLButtonElement|null)[]>([]);
 useEffect(()=>{const controller=new AbortController();setLoading(true);setError('');const q=new URLSearchParams({page:String(page),year:String(year),rankPage:String(rankPage)});if(org)q.set('org',org);fetch('/api/to-chuc-quan-chung?'+q,{signal:controller.signal,cache:'no-store'}).then(async r=>{const d=await r.json();if(!r.ok)throw Error(d.error);if(!controller.signal.aborted)setData(d);}).catch(e=>{if(!controller.signal.aborted)setError(e.message);}).finally(()=>{if(!controller.signal.aborted)setLoading(false);});return()=>controller.abort();},[org,page,year,rankPage,reload]);
 useEffect(()=>{if(!photo){setPreview('');return;}const url=URL.createObjectURL(photo);setPreview(url);return()=>URL.revokeObjectURL(url);},[photo]);
 const selected=org||data?.org||'union',group=groups.find(g=>g.id===selected)!;
 function changeTab(id:string){setOrg(id);setPage(1);}
 async function edit(event?:Activity){setEditorLoading(true);setEditorError('');setQuery('');setPhoto(null);setDraft(event?{id:event.id,version:event.updated_at,org:event.org,title:event.title,date:event.occurred_on,content:event.content,image:event.image,members:event.members.map(m=>m.id)}:{org:selected,title:'',date:new Intl.DateTimeFormat('en-CA',{timeZone:'Asia/Ho_Chi_Minh',year:'numeric',month:'2-digit',day:'2-digit'}).format(new Date()),content:'',image:'',members:[]});requestAnimationFrame(()=>editor.current?.scrollIntoView({behavior:'smooth',block:'start'}));try{const r=await fetch('/api/to-chuc-quan-chung?people=1',{cache:'no-store'});const d=await r.json();if(!r.ok)throw Error(d.error);const list:Person[]=d.people;for(const member of event?.members||[])if(!list.some(p=>p.id===member.id))list.push({...member,active:false});setPeople(list);}catch(e){setPeople([]);setEditorError((e as Error).message);}finally{setEditorLoading(false);}}
 async function save(e:React.FormEvent){e.preventDefault();if(!draft)return;setBusy(true);setEditorError('');try{let image=draft.image;if(photo){const form=new FormData();form.set('file',photo,'activity.webp');image=(await request(form)).path;setDraft(d=>d?{...d,image}:d);setPhoto(null);}await request({...draft,image,op:'save'});setOrg(draft.org);setPage(1);setDraft(null);setNotice('Đã lưu hoạt động và cập nhật số lượt tham gia.');setReload(x=>x+1);}catch(e){setEditorError((e as Error).message);}finally{setBusy(false);}}
 async function remove(event:Activity){if(!window.confirm('Xóa hoạt động này? Các lượt tham gia của hoạt động sẽ được trừ khỏi bảng tổng hợp.'))return;setBusy(true);setError('');try{await request({op:'delete',id:event.id,version:event.updated_at});setNotice('Đã xóa hoạt động.');setReload(x=>x+1);}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 function toggle(id:string){setDraft(d=>d?{...d,members:d.members.includes(id)?d.members.filter(x=>x!==id):[...d.members,id]}:d);}
 return <main className="communityPage communityBoard"><Link href="/" className="communityBack">← Trang chủ</Link><header className="communityHero communityPhotoHero"><div className="communityBannerCopy"><div className="communityBrand"><img src="/logo-snp.webp" alt="Tân Cảng Sài Gòn" width="52" height="56"/><p>TỔNG CÔNG TY TÂN CẢNG SÀI GÒN<span>BINH ĐOÀN 20 · VĂN PHÒNG</span></p></div><h1>Tổ chức<br/>quần chúng</h1><p className="communityBannerMotto">ĐOÀN KẾT · SẺ CHIA · CỐNG HIẾN</p><div className="communityBannerLogos">{groups.map(g=><span key={g.id}><img src={'/community-'+g.id+'.png'} alt={'Logo '+g.short} width="36" height="36"/>{g.short}</span>)}</div></div></header><div className="communityToolbar"><span>{data?.me?`Xin chào, ${data.me.name}`:'Theo dõi hoạt động của các tổ chức Văn phòng'}</span>{data?.me?<button onClick={()=>void edit()} disabled={busy||!!draft}>＋ Thêm hoạt động</button>:<Link href="/dang-nhap?next=/to-chuc-quan-chung">Đăng nhập để cập nhật →</Link>}</div>
 <div className="communityTabs" role="tablist" aria-label="Tổ chức">{groups.map((g,i)=><button key={g.id} ref={el=>{tabs.current[i]=el;}} id={'tab-'+g.id} role="tab" aria-selected={selected===g.id} aria-controls="community-panel" tabIndex={selected===g.id?0:-1} className={'communityTab '+g.id} onClick={()=>changeTab(g.id)} onKeyDown={e=>{let next=i;if(e.key==='ArrowRight')next=(i+1)%3;else if(e.key==='ArrowLeft')next=(i+2)%3;else if(e.key==='Home')next=0;else if(e.key==='End')next=2;else return;e.preventDefault();changeTab(groups[next].id);tabs.current[next]?.focus();}}><img src={'/community-'+g.id+'.png'} alt={'Logo '+g.short} width="46" height="46"/><span><strong>{g.name}</strong><small>{data?.tabs.find(t=>t.org===g.id)?.count||0} hoạt động {data?.tabs[0]?.org===g.id&&<b>· Mới nhất</b>}</small></span></button>)}</div>
 {notice&&<p role="status" className="communityNotice">{notice}</p>}{error&&<div role="alert" className="communityError">{error} <button onClick={()=>setReload(x=>x+1)}>Thử lại</button></div>}
 {draft&&<form ref={editor} className="communityEditor" onSubmit={save}><h2>{draft.id?'Chỉnh sửa hoạt động':'Thêm hoạt động'}</h2><fieldset disabled={busy||editorLoading}><div className="communityFormRow"><label>Tổ chức<select value={draft.org} onChange={e=>setDraft({...draft,org:e.target.value})}>{groups.map(g=><option key={g.id} value={g.id}>{g.name}</option>)}</select></label><label>Ngày hoạt động<input type="date" min="1900-01-01" max="2200-12-31" required value={draft.date} onChange={e=>setDraft({...draft,date:e.target.value})}/></label></div><label>Nội dung chính / tiêu đề<input autoFocus required maxLength={200} value={draft.title} onChange={e=>setDraft({...draft,title:e.target.value})}/></label><label>Thông tin hoạt động<textarea rows={4} maxLength={10000} value={draft.content} onChange={e=>setDraft({...draft,content:e.target.value})}/></label><label>Một ảnh hoạt động · JPG, PNG, WebP nhỏ hơn 10 MB<input type="file" accept="image/jpeg,image/png,image/webp" onChange={async e=>{const f=e.target.files?.[0];e.target.value='';if(!f)return;setBusy(true);setEditorError('');try{setPhoto(await compress(f));}catch(e){setEditorError((e as Error).message);}finally{setBusy(false);}}}/></label>{(preview||draft.image)&&<div className="communityImagePreview"><img src={preview||data!.imageBase+draft.image} alt="Ảnh hoạt động đã chọn"/><button type="button" onClick={()=>{setPhoto(null);setDraft({...draft,image:''});}}>Gỡ ảnh</button></div>}<div className="communityMemberPicker"><label>Tìm thành viên<input ref={selection} type="search" placeholder="Nhập họ tên…" value={query} onChange={e=>setQuery(e.target.value)}/></label><p>Đã chọn {draft.members.length} thành viên · Có thể chọn nhiều người</p><div className="communitySelected">{draft.members.map(id=><button key={id} type="button" onClick={()=>toggle(id)} aria-label={'Bỏ chọn '+(people.find(p=>p.id===id)?.name||'thành viên')}>{people.find(p=>p.id===id)?.name||'Thành viên đã ghi nhận'} ×</button>)}</div><div className="communityPeople">{people.filter(p=>p.name.toLocaleLowerCase('vi').includes(query.toLocaleLowerCase('vi'))).map(p=><label key={p.id}><input type="checkbox" checked={draft.members.includes(p.id)} disabled={p.active===false&&!draft.members.includes(p.id)} onChange={()=>toggle(p.id)}/><span>{p.name}<small>{p.active===false?'Tài khoản cũ · đã ghi nhận':p.position}</small></span></label>)}</div></div><p className="communityHint">Ảnh và danh sách tham gia có thể bổ sung sau. Khi lưu, thành viên được chọn sẽ được ghi nhận tham gia hoạt động.</p><button type="submit">{busy?'Đang lưu…':'Lưu hoạt động'}</button> <button type="button" onClick={()=>{setDraft(null);setPhoto(null);}}>Hủy</button></fieldset>{editorLoading&&<p role="status">Đang tải danh sách tài khoản…</p>}{editorError&&<p role="alert" className="communityError">{editorError}</p>}</form>}
 <section id="community-panel" role="tabpanel" aria-labelledby={'tab-'+selected} aria-busy={loading} className={'communityPanel '+selected}><div className="communitySectionTitle"><h2>{group.name}</h2><span>6 hoạt động / trang</span></div>{loading?<p role="status">Đang tải hoạt động…</p>:data?.events.length?<div className="communityTimeline">{data.events.map(a=><article key={a.id} className="communityActivity"><time dateTime={a.occurred_on}>{dateLabel(a.occurred_on)}</time><div className="communityActivityBody">{a.image?<a href={data.imageBase+a.image} target="_blank" rel="noreferrer" aria-label={'Xem ảnh '+a.title}><img className="communityActivityImage" src={data.imageBase+a.image} loading="lazy" alt={a.title} width="180" height="120"/></a>:<div className="communityActivityPlaceholder"><img src={'/community-'+a.org+'.png'} alt="" width="64" height="64"/></div>}<div className="communityActivityText"><div className="communityPreview"><strong>{a.title}</strong>{a.content&&<span>{" — "+a.content}</span>}</div><div className="communityPreviewFoot"><small>{a.members.length} thành viên tham gia</small><button onClick={()=>setDetail(a)}>Xem chi tiết →</button></div>{data.me&&<div className="communityEditActions"><button onClick={()=>void edit(a)} disabled={busy||!!draft}>Sửa thông tin</button>{data.me.role==='admin'&&<button className="communityDelete" onClick={()=>void remove(a)} disabled={busy}>Xóa</button>}</div>}<AuthorLine activity={a}/></div></div></article>)}</div>:!error&&<p className="communityEmpty">Chưa có hoạt động. {data?.me?'Chọn “Thêm hoạt động” để cập nhật.':''}</p>}{data&&!loading&&<Pager page={data.page} pages={data.pages} onChange={n=>{setPage(n);document.getElementById('community-panel')?.scrollIntoView({behavior:'smooth',block:'start'});}} label="Trang hoạt động"/>}</section>
 <section className="communityRanking rankingCard" aria-labelledby="community-rank-title"><div className="communitySectionTitle"><div><h2 id="community-rank-title">Tổng hợp hoạt động tham gia</h2><p>Cả ba tổ chức · Mỗi hoạt động = 1 điểm / người · Bằng điểm thì đồng hạng</p></div><label>Năm<select aria-label="Năm tổng hợp" value={year} onChange={e=>{setYear(Number(e.target.value));setRankPage(1);}}>{Array.from(new Set([year,...data?.years||[]])).sort((a,b)=>b-a).map(y=><option key={y}>{y}</option>)}</select></label></div>{!loading&&data?.ranking.length?<><div className="tableWrap" role="region" aria-label="Bảng tổng hợp hoạt động" tabIndex={0}><table><thead><tr><th>Hạng</th><th>Họ và tên</th><th>Công đoàn</th><th>Hội Phụ nữ</th><th>Đoàn Thanh niên</th><th>Tổng điểm</th></tr></thead><tbody>{data.ranking.map(r=><tr key={r.person_id} className={r.rank<=3?'podium podium'+r.rank:undefined}><td><div className="rankIdentity">{r.rank<=3?<span className="communityCrown" aria-label={'Hạng '+r.rank}><svg viewBox="0 0 40 32" aria-hidden="true"><path d="M3 7l9 6 8-11 8 11 9-6-5 21H8z" fill="currentColor"/></svg><b>{r.rank}</b></span>:r.rank}<Avatar url={r.photo?data.avatarBase+r.photo:''} name={r.name}/></div></td><td><strong className="rankName">{r.name}</strong><small className="communityPosition">{r.position}</small></td><td>{r.union_count}</td><td>{r.women_count}</td><td>{r.youth_count}</td><td><b>{r.total}</b></td></tr>)}</tbody></table></div><Pager page={data.rankPage} pages={data.rankPages} onChange={setRankPage} label="Trang bảng tổng hợp"/></>:<p>{loading?'Đang tải tổng hợp…':'Chưa có thành viên được ghi nhận trong năm này.'}</p>}</section>{detail&&data&&<ActivityDialog activity={detail} imageBase={data.imageBase} close={()=>setDetail(null)}/>}</main>;
}
function Pager({page,pages,onChange,label}:{page:number;pages:number;onChange:(page:number)=>void;label:string}){if(pages<=1)return null;return <nav className="communityPager" aria-label={label}><button disabled={page<=1} onClick={()=>onChange(page-1)}>← Trước</button><span>Trang {page} / {pages}</span><button disabled={page>=pages} onClick={()=>onChange(page+1)}>Sau →</button></nav>;}
function Avatar({url,name}:{url:string;name:string}){const [failed,setFailed]=useState('');return url&&url!==failed?<span className="rankAvatar"><img src={url} alt={'Ảnh đại diện '+name} width="40" height="40" loading="lazy" onError={()=>setFailed(url)}/></span>:<span className="rankAvatarEmpty" aria-hidden="true"/>;}

function ActivityDialog({activity:a,imageBase,close}:{activity:Activity;imageBase:string;close:()=>void}){const ref=useRef<HTMLDialogElement>(null);useEffect(()=>{const previous=document.activeElement as HTMLElement|null;ref.current?.showModal();return()=>previous?.focus();},[]);return <dialog ref={ref} className="communityDialog" onCancel={close} aria-labelledby="activity-detail-title"><header><span>{dateLabel(a.occurred_on)}</span><button autoFocus onClick={close} aria-label="Đóng chi tiết">Đóng ×</button></header><h2 id="activity-detail-title">{a.title}</h2>{a.image&&<img src={imageBase+a.image} alt={a.title}/>}<p className="communityFullText">{a.content}</p><h3>{a.members.length} thành viên tham gia</h3>{a.members.length?<ul>{a.members.map(m=><li key={m.id}>{m.name}</li>)}</ul>:<p>Chưa bổ sung thành viên.</p>}<AuthorLine activity={a}/></dialog>;}

function AuthorLine({activity}:{activity:Activity}){return <footer className="communityAuthor">Đăng bởi <strong>{activity.author_name||'Tài khoản cũ'}</strong>{activity.created_at&&<> · <time dateTime={activity.created_at}>{new Date(activity.created_at).toLocaleString('vi-VN',{timeZone:'Asia/Ho_Chi_Minh',day:'2-digit',month:'2-digit',year:'numeric',hour:'2-digit',minute:'2-digit'})}</time></>}</footer>;}

