'use client';
import {useEffect,useState} from 'react';
import styles from './Leaderboard.module.css';
type Row={id:string;name:string;photo:string;rank:number;score:number;correct:number;total:number;banks:number;assigned:number;completed:number;exam_points:number;study_points:number;early_points:number};
type Board={rows:Row[];questionTotal:number;asOf:string};
export default function Leaderboard(){
 const [data,setData]=useState<Board|null>(null),[busy,setBusy]=useState(false),[error,setError]=useState(''),[expanded,setExpanded]=useState(false);
 async function refresh(){setBusy(true);setError('');try{const r=await fetch('/api/xep-hang',{cache:'no-store'});const d=await r.json();if(!r.ok)throw Error(d.error);setData(d);}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 useEffect(()=>{void refresh();},[]);
 const rows=data?.rows||[],visible=expanded?rows:rows.slice(0,10);
 return <section className="rankingCard" aria-labelledby="ranking-title"><div className="rankingHeading"><div><h2 id="ranking-title">Bảng xếp hạng học tập</h2><p>Thi thử · Học nghị quyết · Hoàn thành sớm</p></div><button className="secondary" disabled={busy} onClick={()=>void refresh()}>{busy?'Đang tải…':'Cập nhật'}</button></div>
 {error&&<p role="alert">{error}</p>}{!data&&!error&&<p role="status">Đang tổng hợp xếp hạng…</p>}{data&&<><p className="sampleNotice">{rows.length} tài khoản · {data.questionTotal} câu trong danh mục bộ đề · Câu hỏi thi hiện là bản TEST</p><p className="sampleNotice">Điểm thi chỉ tính các bộ đã có kết quả hợp lệ của từng người, mỗi bộ lấy bài tốt nhất.</p><div className="tableWrap" tabIndex={0} role="region" aria-label="Xếp hạng học tập, có thể cuộn ngang"><table className={styles.table}><thead><tr><th>Hạng</th><th>Họ và tên</th><th>Thi thử<small>Tối đa 55</small></th><th>Nghị quyết<small>Tối đa 35</small></th><th>Hoàn thành sớm<small>Tối đa 10</small></th><th>Tổng điểm</th></tr></thead><tbody>{visible.map((r,i)=><tr key={r.id} className={i<10?styles.leading:undefined}><td><div className={styles.identity}><span>{r.rank<=3&&r.score>0?<><svg viewBox="0 0 32 32" aria-hidden="true"><path d="M3 8 10 14 16 4 22 14 29 8 26 27H6Z"/></svg><b>{r.rank}</b></>:r.rank}</span><Avatar row={r}/></div></td><td><span className={r.score>0&&r.rank<=3?styles[('top'+r.rank) as 'top1']:undefined}>{r.name}</span></td><td>{Number(r.exam_points).toFixed(2)}<small>{r.total} câu · {r.total?(100*r.correct/r.total).toFixed(1):'0'}% đúng</small></td><td>{Number(r.study_points).toFixed(2)}<small>{r.assigned?r.completed+'/'+r.assigned+' đợt':'Chưa được giao đợt'}</small></td><td>{Number(r.early_points).toFixed(2)}</td><td>{Number(r.score).toFixed(2)}</td></tr>)}</tbody></table></div>{rows.length===0&&<p>Chưa có tài khoản đang hoạt động.</p>}{rows.length>10&&<button className={styles.expand} aria-expanded={expanded} onClick={()=>setExpanded(!expanded)}>{expanded?'Thu gọn còn 10 tài khoản đầu':'Xem '+(rows.length-10)+' tài khoản còn lại'}</button>}</>}
 <details className={styles.formula}><summary>Cách tính điểm 50 – 30 – 20</summary><p>Thi thử: mỗi bộ lấy một bài hợp lệ có tỷ lệ đúng cao nhất; bằng tỷ lệ ưu tiên thời gian ngắn hơn. Chỉ tính bài đã hoàn thành, gắn với tài khoản và thuộc gói đủ điều kiện xếp hạng. Số câu đúng cộng từ các bài tốt nhất chia tổng số câu của các bộ tính điểm, nhân 50. Bộ chưa thi nhận 0 điểm; thi lặp không cộng thêm số câu.</p><p>Nghị quyết: số đợt hoàn thành chia số đợt được giao đã phát hành, nhân 30. Không tính đợt nháp hoặc đã xóa.</p><p>Hoàn thành sớm: trong từng đợt và cùng nhóm đảng viên/quần chúng, người hoàn thành đầu tiên đạt 100%; các vị trí sau giảm đều theo số người được giao, vị trí cuối đạt 0%. Cùng thời điểm thì cùng mức điểm. Chưa hoàn thành tính 0; nhóm chỉ một người hoàn thành đạt 100%. Lấy bình quân trên các đợt được giao rồi nhân 20.</p><p>Chưa được giao nghị quyết: hai phần điểm nghị quyết tạm bằng 0. Tổng tối đa 100; bằng tổng điểm thì đồng hạng, thứ tự tên chỉ dùng để hiển thị. Mặc định hiện 10 tài khoản đầu. Không tự gán kết quả khách hoặc kết quả cũ thiếu liên kết tài khoản theo tên.</p></details>{data?.asOf&&<small>Cập nhật: {new Date(data.asOf).toLocaleString('vi-VN')}</small>}</section>;
}
function Avatar({row}:{row:Row}){const [failed,setFailed]=useState('');return row.photo&&failed!==row.photo?<img src={row.photo} alt={'Ảnh đại diện '+row.name} width="32" height="32" loading="lazy" onError={()=>setFailed(row.photo)}/>:<span className={styles.avatar} aria-hidden="true"/>;}

