'use client';
import {useEffect,useState} from 'react';
import Icon from './Icon';
type Row={name:string;correct:number;total:number;elapsed:number;rank:number};
export default function Leaderboard(){
 const [data,setData]=useState<{ready:boolean;max:number;rows:Row[];message?:string;asOf?:string}|null>(null);const [busy,setBusy]=useState(false);
 async function refresh(){setBusy(true);try{const r=await fetch('/api/thi-thu');setData(await r.json());}catch{setData({ready:false,max:0,rows:[],message:'Chưa tải được bảng xếp hạng. Vui lòng thử lại.'});}finally{setBusy(false);}}
 useEffect(()=>{void refresh();},[]);
 return <section className="rankingCard" id="ranking" aria-labelledby="ranking-title"><div className="rankingHeading"><div className="rankingLabel"><span className="trophy"><Icon name="trophy"/></span><div><h2 id="ranking-title">Bảng xếp hạng Thi thử</h2><p>Nhận thức chính trị · TEST {data?.max?`· Gói ${data.max} câu`:''}</p></div></div><button className="secondary" disabled={busy} onClick={()=>void refresh()}>{busy?'Đang tải…':'Cập nhật'}</button></div>{!data?.ready?<div className="emptyRanking" role="status"><strong>{data?.message||'Đang tải kết quả…'}</strong><p>Không hiển thị thành tích mẫu. Ôn tập không tính xếp hạng.</p></div>:data.rows.length===0?<div className="emptyRanking"><strong>Chưa có kết quả cho gói này</strong><p>Hãy thử sức với gói {data.max} câu và ghi dấu thành tích đầu tiên!</p></div>:<><p className="sampleNotice">Kết quả từ bộ câu hỏi TEST · Chưa dùng chính thức</p><div className="tableWrap" tabIndex={0} role="region" aria-label="Bảng xếp hạng có thể cuộn ngang"><table><thead><tr><th>Hạng</th><th>Họ và tên</th><th>Điểm</th><th>Thời gian</th></tr></thead><tbody>{data.rows.map((r,i)=><tr key={i} className={r.rank <= 3 ? `podium podium${r.rank}` : undefined}><td><span className={`rank rank${r.rank}`}>{r.rank}</span></td><td>{r.name}</td><td><b>{r.correct}/{r.total}</b></td><td>{Math.floor(r.elapsed/60)}:{String(r.elapsed%60).padStart(2,'0')}</td></tr>)}</tbody></table></div></>}<div className="emptyRanking"><p>Chỉ gói lớn nhất đang mở của chuyên đề được xếp hạng. Giữ thành tích tốt nhất của mỗi hồ sơ trình duyệt; bằng điểm ưu tiên thời gian ngắn hơn, bằng cả hai thì đồng hạng. Bảng hiển thị tối đa 30 hồ sơ dẫn đầu.</p>{data?.asOf&&<p>Cập nhật: {new Date(data.asOf).toLocaleString('vi-VN')}</p>}</div></section>;
}
