'use client';
import {useEffect,useState} from 'react';
import Icon from './Icon';
type Row={name:string;correct:number;total:number;elapsed:number;rank:number};
export default function Leaderboard(){
 const [data,setData]=useState<{ready:boolean;max:number;rows:Row[];message?:string;asOf?:string}|null>(null);const [busy,setBusy]=useState(false);
 async function refresh(){setBusy(true);try{const r=await fetch('/api/thi-thu');setData(await r.json());}catch{setData({ready:false,max:0,rows:[],message:'Chưa tải được bảng xếp hạng. Vui lòng thử lại.'});}finally{setBusy(false);}}
 useEffect(()=>{void refresh();},[]);
 return <section className="rankingCard" id="ranking" aria-labelledby="ranking-title"><div className="rankingHeading"><div className="rankingLabel"><span className="trophy"><Icon name="trophy"/></span><div><h2 id="ranking-title">Bảng xếp hạng Thi thử</h2><p>Nhận thức chính trị · TEST {data?.max?`· Gói ${data.max} câu`:''}</p></div></div><button className="secondary" disabled={busy} onClick={()=>void refresh()}>{busy?'Đang tải…':'Cập nhật'}</button></div>{!data?.ready?<div className="emptyRanking" role="status"><strong>{data?.message||'Đang tải kết quả…'}</strong><p>Không hiển thị thành tích mẫu. Ôn tập không tính xếp hạng.</p></div>:data.rows.length===0?<div className="emptyRanking"><strong>Chưa có kết quả cho gói này</strong><p>Hãy thử sức với gói {data.max} câu và ghi dấu thành tích đầu tiên!</p></div>:<><p className="sampleNotice">Kết quả từ bộ câu hỏi TEST · Chưa dùng chính thức</p><div className="tableWrap" tabIndex={0} role="region" aria-label="Bảng xếp hạng có thể cuộn ngang"><table><thead><tr><th>Hạng</th><th>Họ và tên</th><th>Điểm</th><th>Thời gian</th></tr></thead><tbody>{data.rows.map((r,i)=><tr key={i} className={r.rank <= 3 ? `podium podium${r.rank}` : undefined}><td>{r.rank<=3?<CrownRank rank={r.rank}/>:<span className="rank">{r.rank}</span>}</td><td><span className="rankName">{r.name}</span></td><td><b>{r.correct}/{r.total}</b></td><td>{Math.floor(r.elapsed/60)}:{String(r.elapsed%60).padStart(2,'0')}</td></tr>)}</tbody></table></div></>}<div className="emptyRanking"><p>Chỉ gói lớn nhất đang mở của chuyên đề được xếp hạng. Giữ thành tích tốt nhất của mỗi hồ sơ trình duyệt; bằng điểm ưu tiên thời gian ngắn hơn, bằng cả hai thì đồng hạng. Bảng hiển thị tối đa 30 hồ sơ dẫn đầu.</p>{data?.asOf&&<p>Cập nhật: {new Date(data.asOf).toLocaleString('vi-VN')}</p>}</div></section>;
}

function CrownRank({rank}:{rank:number}){return <span className={`crownRank crownRank${rank}`} aria-label={`Hạng ${rank}`}><svg viewBox="0 0 100 100" aria-hidden="true"><defs><linearGradient id={`crownMetal${rank}`} x2=".7" y2="1"><stop stopColor={rank===1?'#fff6b7':rank===2?'#f5ffff':'#ffe1b6'}/><stop offset=".45" stopColor={rank===1?'#f5c447':rank===2?'#9fbcd7':'#de9966'}/><stop offset="1" stopColor={rank===1?'#996013':rank===2?'#446488':'#8d452c'}/></linearGradient></defs>{rank===1?<><path d="M13 35 29 43 35 21 50 36 65 21 71 43 87 35 79 62H21Z"/><path d="M22 66Q50 56 78 66L75 82Q50 94 25 82Z"/><circle cx="35" cy="18" r="4"/><circle cx="65" cy="18" r="4"/></>:rank===2?<><path d="M17 34 35 44 50 18 65 44 83 34 76 65H24Z"/><path d="M25 69H75L68 85 50 95 32 85Z"/><path d="m50 8 5 6-5 6-5-6Z"/></>:<><path d="M19 39 34 48 42 29 50 41 58 29 66 48 81 39 74 65H26Z"/><ellipse cx="50" cy="78" rx="26" ry="17"/><path d="M14 60Q5 84 25 91M86 60Q95 84 75 91" fill="none"/></>}<path d="M27 58H73" fill="none" stroke="#fff9d8" strokeWidth="2"/></svg><b>{rank}</b></span>;}
