'use client';
import {useState} from 'react';
export type DirectoryPerson={id:string;name:string;username:string;audience:'party'|'public';created_at:string;study_count:number};
export default function MemberDirectory({people}:{people:DirectoryPerson[]}){
 const [query,setQuery]=useState('');
 const clean=(s:string)=>s.normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/đ/g,'d').replace(/Đ/g,'D').toLowerCase();
 const ordered=people.slice().sort((a,b)=>a.audience.localeCompare(b.audience)||a.created_at.localeCompare(b.created_at)||a.id.localeCompare(b.id));
 const rows=ordered.filter(p=>clean(p.name+' '+p.username).includes(clean(query.trim())));
 return <section className="memberDirectory" aria-labelledby="directory-title"><header><p>VĂN PHÒNG TỔNG CÔNG TY</p><h2 id="directory-title">Tra cứu tài khoản học tập</h2><span>Dành cho đảng viên và quần chúng. Mật khẩu được thông báo riêng.</span></header><label className="directorySearch">Tìm họ tên hoặc tên tài khoản<input type="search" value={query} onChange={e=>setQuery(e.target.value)} placeholder="Nhập họ tên hoặc tên tài khoản…"/></label><div className="directoryTableWrap"><table><thead><tr><th scope="col">STT</th><th scope="col">Họ tên</th><th scope="col">Tên tài khoản</th><th scope="col" className="studyCountColumn">Lượt học nghị quyết</th></tr></thead><tbody>{(['party','public'] as const).map(group=>{const members=rows.filter(p=>p.audience===group);return members.length?<DirectoryGroup key={group} group={group} members={members} ordered={ordered}/>:null;})}</tbody></table></div>{rows.length===0&&<p className="directoryEmpty">Chưa có tài khoản phù hợp.</p>}<p className="directoryFoot">{people.length} người học · Mỗi đợt hoàn thành tính một lượt; học lại không cộng trùng. Giữ thứ tự tạo tài khoản trong từng nhóm.</p></section>;
}
function DirectoryGroup({group,members,ordered}:{group:string;members:DirectoryPerson[];ordered:DirectoryPerson[]}){return <><tr className="directoryGroup"><th colSpan={4} scope="rowgroup">{group==='party'?'Đảng viên':'Quần chúng'}</th></tr>{members.map(p=><tr key={p.id}><td>{ordered.findIndex(x=>x.id===p.id)+1}</td><th scope="row">{p.name}</th><td><code>{p.username}</code></td><td className="studyCountColumn"><strong className="studyCountMedal">{Number(p.study_count).toLocaleString('vi-VN')}</strong><small>đợt hoàn thành</small></td></tr>)}</>;}
