 'use client';
import {useEffect,useRef,useState} from 'react';
import Link from 'next/link';
import {politicsAudiences,newPractice,beginPractice,advancePractice,type PracticeState,type PoliticsQuestion} from '../lib/politics-config';
import s from './PoliticsStudy.module.css';
import {queuePracticeCompletion,flushPracticeCompletions} from '../lib/politics-activity-client';
type Bank={id:string;title:string;count:number;version:string;ready:boolean};
type Exam={id:string;audience:string;full:boolean;cursor:number;total:number;deadline:string;now:string;status:string;timeouts:number;correct:number;question:PoliticsQuestion|null;review:PoliticsQuestion[];answers:Record<string,string>};
type Meta={banks:Bank[];me:{id:string;name:string;role:string}|null;permission:string|null;active:string|null;pendingStudy?:{total:number;open:number;closed:number}|null};
const api='/api/nhan-thuc-chinh-tri';
async function request(payload:unknown){const r=await fetch(api,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(payload)});const d=await r.json();if(!r.ok)throw Error(d.error);return d;}
export default function PoliticsStudy(){
 const [meta,setMeta]=useState<Meta|null>(null),[mode,setMode]=useState('practice'),[audience,setAudience]=useState(''),[questions,setQuestions]=useState<PoliticsQuestion[]>([]),[practice,setPractice]=useState<PracticeState|null>(null),[key,setKey]=useState(''),[exam,setExam]=useState<Exam|null>(null),[answer,setAnswer]=useState(''),[busy,setBusy]=useState(false),[error,setError]=useState(''),[feedback,setFeedback]=useState(''),[tick,setTick]=useState(0),[people,setPeople]=useState<{id:string;name:string;username:string}[]>([]),[permissions,setPermissions]=useState<Record<string,string>>({}),[adminOpen,setAdminOpen]=useState(false),[notice,setNotice]=useState('');
 const [activityPending,setActivityPending]=useState(false);
 async function flushActivity(){setActivityPending(!await flushPracticeCompletions());}
 function recordPractice(state:PracticeState,bankId:string){if(state.round?.status==='done'){state.round.id??=crypto.randomUUID();try{queuePracticeCompletion({id:state.round.id,audience:bankId,questionIds:state.round.ids});void flushActivity();}catch{setActivityPending(true);}}}
 useEffect(()=>{void flushActivity();const online=()=>void flushActivity();window.addEventListener('online',online);const timer=setInterval(online,30000);return()=>{clearInterval(timer);window.removeEventListener('online',online);};},[]);
 const questionPanel=useRef<HTMLElement>(null);
 const [focusRequest,setFocusRequest]=useState(0);
 useEffect(()=>{if(focusRequest){questionPanel.current?.focus({preventScroll:true});questionPanel.current?.scrollIntoView({block:'start',behavior:'instant'});}},[focusRequest]);
 const anchor=useRef({server:Date.now(),perf:0}),pending=useRef(false);
 async function load(){const r=await fetch(api,{cache:'no-store'});const d=await r.json();if(!r.ok)throw Error(d.error);setMeta(d);}
 useEffect(()=>{const q=new URLSearchParams(location.search);if(q.get('mode')==='exam')setMode('exam');load().catch(e=>setError(e.message));const refresh=()=>{if(document.visibilityState==='visible')load().catch(()=>{});};document.addEventListener('visibilitychange',refresh);return()=>document.removeEventListener('visibilitychange',refresh);},[]);
 useEffect(()=>{const timer=setInterval(()=>setTick(x=>x+1),1000);return()=>clearInterval(timer);},[]);
 function savePractice(next:PracticeState,storageKey=key,bankId=audience){if(next.round)next.round.id??=crypto.randomUUID();recordPractice(next,bankId);setPractice(next);try{localStorage.setItem(storageKey,JSON.stringify(next));}catch{setError('Trình duyệt không lưu được tiến độ. Không đóng trang khi đang ôn.');}}
 useEffect(()=>{if(practice?.round?.status==='active'){const next=advancePractice(practice,questions,Date.now());if(next.round?.index!==practice.round.index||next.round?.status!==practice.round.status){savePractice(next);if(mode==='practice')setAnswer('');}}},[tick]);
 async function syncExam(payload:unknown){if(pending.current)return;pending.current=true;setBusy(true);setError('');try{const d=await request(payload);anchor.current={server:Date.parse(d.now),perf:performance.now()};setExam(d);setAnswer('');await load();}catch(e){setError((e as Error).message);}finally{pending.current=false;setBusy(false);}}
 useEffect(()=>{const resume=()=>{if(document.visibilityState==='visible'&&exam?.status==='active')void syncExam({op:'resume',id:exam.id});};document.addEventListener('visibilitychange',resume);return()=>document.removeEventListener('visibilitychange',resume);},[exam?.id,exam?.status]);
 const examNow=anchor.current.server+(typeof performance==='undefined'?0:performance.now()-anchor.current.perf);
 const seconds=mode==='exam'&&exam?Math.max(0,Math.ceil((Date.parse(exam.deadline)-examNow)/1000)):Math.max(0,Math.ceil(((practice?.round?.deadline||Date.now())-Date.now())/1000));
 useEffect(()=>{if(exam?.status==='active'&&Date.parse(exam.deadline)<=examNow&&!busy&&tick%3===0)void syncExam({op:'resume',id:exam.id});},[tick]);
 async function choosePractice(b:Bank,count:number){setBusy(true);setError('');setNotice('');setFeedback('');setAnswer('');try{const r=await fetch(api+'?mode=practice&audience='+b.id,{cache:'no-store'});const d=await r.json();if(!r.ok)throw Error(d.error);const storageKey='politics-practice-v1:'+b.id+':'+d.version;let state=newPractice(d.questions.map((q:PoliticsQuestion)=>q.id));try{const stored=JSON.parse(localStorage.getItem(storageKey)||'null');if(stored&&Array.isArray(stored.remaining)&&Array.isArray(stored.wrong)&&typeof stored.completed==='number'&&stored.remaining.every((id:string)=>d.questions.some((q:PoliticsQuestion)=>q.id===id))){state=advancePractice(stored,d.questions,Date.now());}}catch{}recordPractice(state,b.id);if(state.round?.status==='active'){if(state.round.ids.length!==count)setNotice(`Tiếp tục lượt ${state.round.ids.length} câu đang làm. Hoàn thành lượt này để chọn gói khác; thời gian được giữ nguyên.`);}else if(state.remaining.length||state.wrong.length){state=beginPractice(state,count);}else{setNotice('Bạn đã hoàn thành toàn bộ bộ câu hỏi. Chọn Bắt đầu chu trình mới nếu muốn ôn lại.');}setKey(storageKey);setQuestions(d.questions);setAudience(b.id);savePractice(state,storageKey,b.id);setFocusRequest(n=>n+1);}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 async function adminLoad(){setError('');try{const r=await fetch(api+'?mode=admin',{cache:'no-store'});const d=await r.json();if(!r.ok)throw Error(d.error);setPeople(d.people);setPermissions(Object.fromEntries(d.permissions.map((x:{person_id:string;audience:string})=>[x.person_id,x.audience])));setAdminOpen(true);}catch(e){setError((e as Error).message);}}
 async function assign(person:string,value:string){setBusy(true);setError('');try{await request({op:'assign',person,audience:value});setPermissions(p=>({...p,[person]:value}));setNotice('Đã lưu quyền thi. Đổi đối tượng sẽ dừng lượt thi đang làm của người này.');await load();}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 const round=practice?.round,q=mode==='exam'?exam?.question:round?.status==='active'?questions.find(q=>q.id===round.ids[round.index]):null;
 const active=mode==='exam'?exam?.status==='active':round?.status==='active';
 return <main className={s.page}><div className={s.top}><Link href="/">← Trang chủ</Link><button onClick={async()=>{try{await navigator.clipboard.writeText(location.origin+'/nhan-thuc-chinh-tri');setNotice('Đã sao chép đường dẫn học phần.');}catch{setNotice('Đường dẫn chia sẻ: '+location.origin+'/nhan-thuc-chinh-tri');}}}>Sao chép đường dẫn ↗</button></div>
 <header className={s.hero}><img src="/logo-snp.webp" width="66" height="72" alt="SNP"/><p>VĂN PHÒNG TỔNG CÔNG TY</p><h1>Ôn tập và Thi thử<span>phục vụ Kiểm tra nhận thức chính trị</span><b>năm 2026</b></h1></header>
 <div className={s.rules}>Mỗi câu tối đa <b>2 phút</b> · <b>10 câu liên tiếp hết giờ</b> sẽ dừng lượt · Đổi tab hoặc tải lại trang không đặt lại thời gian.</div>
 {notice&&<p className={s.notice} role="status">{notice}</p>}{error&&<p className={s.error} role="alert">{error} {!meta&&<button onClick={()=>load().catch(e=>setError(e.message))}>Tải lại</button>}</p>}
 {meta?.me&&<aside className={s.studyReminder} aria-label="Nhắc nghiên cứu nghị quyết">{meta.pendingStudy?<><span>{meta.pendingStudy.total>0?<>Bạn còn <b>{meta.pendingStudy.total} đợt nghiên cứu nghị quyết</b> chưa hoàn thành.{meta.pendingStudy.closed>0&&<> Trong đó {meta.pendingStudy.closed} đợt đã đóng; {meta.pendingStudy.open} đợt đang mở.</>}</>:<>Bạn không còn đợt nghiên cứu nghị quyết nào chưa hoàn thành.</>}</span><Link href="/hoc-tap">{meta.pendingStudy.total?'Xem các đợt nghiên cứu →':'Xem học tập nghị quyết →'}</Link></>:<><span>Chưa tải được số đợt nghiên cứu nghị quyết chưa hoàn thành.</span><Link href="/hoc-tap">Kiểm tra tại mục học tập →</Link></>}</aside>}
 {activityPending&&<p className={s.note} role="status">Lượt ôn đã lưu trên trình duyệt, đang chờ đồng bộ bộ đếm học tập và trang A4. Hệ thống sẽ thử lại khi có kết nối. <button onClick={()=>void flushActivity()}>Thử đồng bộ</button></p>}
 <div className={s.tabs}><button aria-pressed={mode==='practice'} onClick={()=>{setMode('practice');setAnswer('');}}>Ôn tập tự do</button><button aria-pressed={mode==='exam'} onClick={()=>{setMode('exam');setAnswer('');}}>Thi thử theo đối tượng</button>{meta?.me?.role==='admin'&&<button onClick={()=>adminOpen?setAdminOpen(false):void adminLoad()}>Cấp quyền thi</button>}</div>
 {adminOpen&&<section className={s.panel}><h2>Cấp quyền thi Nhận thức chính trị</h2><p>Quyền này độc lập với đối tượng học nghị quyết. Mỗi tài khoản có một đối tượng thi.</p><div className={s.people}>{people.map(p=><label key={p.id}><span>{p.name} <small>({p.username})</small></span><select aria-label={'Quyền thi của '+p.username} disabled={busy} value={permissions[p.id]||''} onChange={e=>void assign(p.id,e.target.value)}><option value="">Chưa cấp quyền</option>{politicsAudiences.map(a=><option key={a.id} value={a.id}>{a.title}</option>)}</select></label>)}</div></section>}
 {mode==='practice'&&<><p className={s.intro}>Chọn gói 20, 50 hoặc 100 câu trong bộ muốn ôn để bắt đầu ngay, không cần đăng nhập. Hệ thống ưu tiên câu chưa ôn; hết bộ thì luyện lại câu sai. Tiến độ lưu riêng trên trình duyệt này.</p><div className={s.cards}>{(meta?.banks||politicsAudiences.map(a=>({...a,count:0,version:'',ready:false}))).map(b=><article key={b.id} className={audience===b.id?s.selected:''}><h2>{b.title}</h2><strong>{b.ready?b.count+' câu':'Chưa có bộ đề'}</strong>{b.ready?<div className={s.packages} role="group" aria-label={'Gói ôn '+b.title}>{[20,50,100].map(n=><button key={n} disabled={busy} onClick={()=>void choosePractice(b,n)}><b>{n}</b><span>câu</span></button>)}</div>:<button disabled>Chờ bổ sung</button>}</article>)}</div>
 {practice&&<section className={s.panel}><h2>{politicsAudiences.find(a=>a.id===audience)?.title}</h2><p>Đã ôn {practice.completed}/{questions.length} câu · Chưa ôn: {practice.remaining.length} · Cần ôn lại: {practice.wrong.length}</p>{!active&&<>{round?.status==='aborted'&&<p className={s.error}>Đã dừng vì 10 câu liên tiếp hết giờ. Làm lại lượt này; các lượt hoàn thành trước vẫn được giữ.</p>}{round?.status==='done'&&<p className={s.notice}>Hoàn thành lượt: {round.ids.filter(id=>round.answers[id]===questions.find(q=>q.id===id)?.correct_answer).length}/{round.ids.length} câu đúng.</p>}{(practice.remaining.length||practice.wrong.length)?<div className={s.actions}>{(round?.status==='aborted'?[round.ids.length]:[...new Set([20,50,100].map(n=>Math.min(n,practice.remaining.length||practice.wrong.length)))]).map(n=><button key={n} className={s.primary} onClick={()=>{savePractice(beginPractice(practice,n));setFeedback('');setAnswer('');setFocusRequest(x=>x+1);}}>{round?.status==='aborted'?`Ôn lại lượt ${n} câu bị dừng`:practice.remaining.length?`Ôn tiếp ${n} câu chưa ôn`:`Ôn lại ${n} câu sai`}</button>)}</div>:<p>Đã trả lời đúng toàn bộ câu hỏi trong chu trình.</p>} <button onClick={()=>{if(confirm('Bắt đầu chu trình mới và xóa tiến độ ôn bộ này trên trình duyệt?'))savePractice(newPractice(questions.map(q=>q.id)));}}>Bắt đầu chu trình mới</button></>}</section>}</>}
 {mode==='exam'&&<section className={s.panel}><h2>Thi đúng đối tượng được cấp quyền</h2>{!meta?.me?<><p>Đăng nhập để hệ thống xác định bộ đề được thi.</p><Link className={s.primary} href="/dang-nhap?next=%2Fnhan-thuc-chinh-tri%3Fmode%3Dexam">Đăng nhập →</Link></>:<><p>{meta.me.name} · {politicsAudiences.find(a=>a.id===meta.permission)?.title||'Chưa được cấp quyền thi. Liên hệ cán bộ phụ trách.'}</p>{meta.active&&!active&&<button disabled={busy} onClick={()=>void syncExam({op:'resume',id:meta.active})}>Tiếp tục lượt thi đang làm</button>}{!meta.active&&!active&&meta.permission&&<>{!meta.banks.find(b=>b.id===meta.permission)?.ready?<p>Bộ đề đối tượng này đang chờ bổ sung.</p>:<div className={s.actions}><button className={s.primary} disabled={busy} onClick={()=>void syncExam({op:'start',audience:meta.permission,package:'100'})}>Thi {Math.min(100,meta.banks.find(b=>b.id===meta.permission)?.count||100)} câu ngẫu nhiên</button><button disabled={busy} onClick={()=>void syncExam({op:'start',audience:meta.permission,package:'all'})}>Thi toàn bộ {meta.banks.find(b=>b.id===meta.permission)?.count} câu</button></div>}</>}<p className={s.note}>Chỉ lượt hoàn thành gói toàn bộ được tính xếp hạng. Lượt bị dừng không tính. Đáp án hiện sau khi hoàn thành.</p></>}{exam?.status==='aborted'&&<p className={s.error}>Lượt thi đã dừng. Nếu 10 câu liên tiếp hết giờ hoặc quyền thi thay đổi, cần bắt đầu lại; lượt này không tính xếp hạng.</p>}{exam?.status==='done'&&<p className={s.notice}>Kết quả: {exam.correct}/{exam.total} câu đúng ({(100*exam.correct/exam.total).toFixed(1)}%).</p>}</section>}
 {active&&q&&<section ref={questionPanel} tabIndex={-1} className={s.panel} aria-label="Câu hỏi đang làm"><div className={s.progress}><b>Câu {(mode==='exam'?exam!.cursor:round!.index)+1}/{mode==='exam'?exam!.total:round!.ids.length}</b><strong className={seconds<20?s.red:''}>{Math.floor(seconds/60)}:{String(seconds%60).padStart(2,'0')}</strong><span>Hết giờ liên tiếp: {mode==='exam'?exam!.timeouts:round!.timeouts}/10</span></div>{feedback&&mode==='practice'&&<p className={s.notice} role="status">{feedback}</p>}<h2>{q.question}</h2><p className={s.note}>Câu {q.number} trong tài liệu gốc · {q.source.location}</p><fieldset disabled={busy} className={s.options}><legend>Chọn một đáp án</legend>{Object.entries(q.options).map(([k,v])=><label key={k} className={answer===k?s.checked:''}><input type="radio" name="politics-answer" value={k} checked={answer===k} onChange={()=>setAnswer(k)}/><b>{k.replace(/^([A-ZĐ])2$/, '$1 (2)')}.</b><span>{v}</span></label>)}</fieldset><div className={s.actions}><button className={s.primary} disabled={!answer||busy||seconds<=0} onClick={()=>{if(mode==='exam')void syncExam({op:'answer',id:exam!.id,cursor:exam!.cursor,answer});else{const next=advancePractice(practice!,questions,Date.now(),answer);savePractice(next);setFeedback(next.round?.answers[q.id]===answer?(answer===q.correct_answer?'Câu trước: trả lời đúng.':'Câu trước: chưa đúng. Đáp án '+q.correct_answer+': '+q.options[q.correct_answer]):'Câu trước đã hết thời gian.');setAnswer('');}}}>{busy?'Đang lưu…':'Xác nhận trả lời →'}</button>{mode==='exam'&&<button disabled={busy} onClick={()=>{if(confirm('Dừng và bỏ kết quả lượt thi này?'))void syncExam({op:'discard',id:exam!.id});}}>Dừng lượt thi</button>}</div></section>}
 {((mode==='exam'&&exam?.status==='done')||(mode==='practice'&&round?.status==='done'))&&<details className={s.panel}><summary>Xem đáp án của lượt vừa hoàn thành</summary>{(mode==='exam'?exam!.review:questions.filter(q=>round!.ids.includes(q.id))).map(q=><article className={s.review} key={q.id}><b>Câu {q.number}. {q.question}</b><p>Đã chọn: {(mode==='exam'?exam!.answers:round!.answers)[q.id]||'Hết giờ / chưa trả lời'} · Đáp án: {q.correct_answer}</p><p>{q.options[q.correct_answer]}</p><small>{q.source.location}</small></article>)}</details>}
 </main>;
}

