'use client';
import {useEffect,useState} from 'react';
import {bookTopics,excelHeaders,validateQuestions,type QuestionBook} from '../lib/question-books';
import type {Question} from '../lib/practice';
import {invalidateBooks} from './QuestionBooks';
export default function QuestionBookAdmin(){
 const [builtinTitle,setBuiltinTitle]=useState(''),[builtinDate,setBuiltinDate]=useState('');
 const [books,setBooks]=useState<QuestionBook[]>([]),[topic,setTopic]=useState('law'),[title,setTitle]=useState(''),[questions,setQuestions]=useState<Question[]>([]),[busy,setBusy]=useState(false),[message,setMessage]=useState('');
 async function load(){const r=await fetch('/api/bo-de?manage=1',{cache:'no-store'});const d=await r.json();if(!r.ok)throw Error(d.error);setBooks(d.books);setBuiltinTitle(d.builtin?.title||'');setBuiltinDate(d.builtin?.updated_on||'');}
 useEffect(()=>{void load().catch(e=>setMessage(e.message));},[]);
 async function parse(file:File|undefined){setQuestions([]);setMessage('');if(!file)return;setBusy(true);try{if(!file.name.toLowerCase().endsWith('.xlsx')||file.size>2*1024*1024)throw Error('Chọn tệp .xlsx tối đa 2 MB.');const Excel=await import('exceljs');const workbook=new Excel.Workbook();await workbook.xlsx.load(await file.arrayBuffer());const sheet=workbook.getWorksheet('CauHoi');if(!sheet||sheet.rowCount>501)throw Error('Cần sheet CauHoi, tối đa 500 câu.');
 const cell=(row:number,col:number)=>{const c=sheet.getCell(row,col);if(c.type===Excel.ValueType.Formula)throw Error(`Dòng ${row}: không dùng công thức Excel.`);return c.text.trim();};
 excelHeaders.forEach((h,i)=>{if(cell(1,i+1)!==h)throw Error('Không thay đổi hàng tiêu đề trong mẫu Excel.');});
 const rows=[];for(let row=2;row<=sheet.rowCount;row++){const cells=excelHeaders.map((_,i)=>cell(row,i+1));if(cells.every(x=>!x))continue;rows.push({id:cells[0],section:cells[1],question:cells[2],options:{A:cells[3],B:cells[4],C:cells[5],D:cells[6]},correct_answer:cells[7].toUpperCase(),explanation:cells[8],source:{location:cells[9]}});}
 const valid=validateQuestions(rows);setQuestions(valid);setMessage(`Đã kiểm tra ${valid.length} câu. Xem trước rồi bấm Lưu bản nháp.`);
 }catch(e){setMessage((e as Error).message);}finally{setBusy(false);}}
 async function action(payload:unknown){setBusy(true);setMessage('');try{const r=await fetch('/api/bo-de',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(payload)});const d=await r.json();if(!r.ok)throw Error(d.error);invalidateBooks();await load();setMessage('Đã cập nhật bộ đề.');return true;}catch(e){setMessage((e as Error).message);return false;}finally{setBusy(false);}}
 return <section className="practicePanel"><h2>Quản lý bộ câu hỏi</h2><p>Mẫu Excel dùng cho 5 học phần ngoài Nhận thức chính trị. Mỗi câu có 4 phương án, 1 đáp án đúng. Nội dung đã lưu không bị sửa đè; cần sửa thì tải bộ mới và thu hồi bộ cũ.</p><a href="/mau-bo-cau-hoi.xlsx" download>Tải mẫu Excel nhập câu hỏi</a><form onSubmit={async e=>{e.preventDefault();if(await action({op:'upload',topic,title,questions})){setQuestions([]);setTitle('');}}}><fieldset disabled={busy}><label>Học phần<select value={topic} onChange={e=>setTopic(e.target.value)}>{bookTopics.map(t=><option value={t.key} key={t.key}>{t.title}</option>)}</select></label><label>Tên bộ đề<input required maxLength={180} value={title} onChange={e=>setTitle(e.target.value)} placeholder="Ví dụ: Quy chế làm việc – Bộ 01"/></label><label>Tệp Excel<input type="file" accept=".xlsx" onChange={e=>{void parse(e.target.files?.[0]);e.target.value='';}}/></label>{questions.length>0&&<details open><summary>Xem trước: {questions.length} câu</summary>{questions.slice(0,3).map(q=><article key={q.id}><strong>{q.id}. {q.question}</strong><p>{Object.entries(q.options).map(([k,v])=>`${k}. ${v}`).join(' · ')}</p><small>Đáp án đúng: {q.correct_answer} · {q.source.location}</small></article>)}</details>}<button disabled={!questions.length} type="submit">Lưu bản nháp</button></fieldset></form>{message&&<p role="status">{message}</p>}<details><summary>Tên và ngày cập nhật bộ Nhận thức chính trị hiện tại</summary><p>Chỉ cập nhật thông tin hiển thị; không thay đổi câu hỏi hoặc cách thi của học phần này. Nhập đúng ngày cập nhật thực tế.</p><label>Tên bộ hiện tại<input maxLength={180} value={builtinTitle} onChange={e=>setBuiltinTitle(e.target.value)}/></label><label>Ngày cập nhật<input type="date" value={builtinDate} onChange={e=>setBuiltinDate(e.target.value)}/></label><button disabled={busy||!builtinDate||!builtinTitle.trim()} onClick={()=>void action({op:'builtinMetadata',title:builtinTitle,date:builtinDate})}>Lưu thông tin hiển thị</button></details><h3>Các bộ đã tải</h3>{books.map(b=><article key={b.id} style={{padding:'14px 0',borderBottom:'1px solid #d5dfe5'}}><strong>{b.title}</strong><p>{bookTopics.find(t=>t.key===b.topic)?.title} · {b.question_count} câu · {b.status==='published'?'Đã công bố':'Bản nháp'}</p><button disabled={busy} onClick={()=>{if(confirm(b.status==='published'?'Thu hồi bộ này khỏi danh sách cho lượt học mới? Kết quả và lượt thi đang làm được giữ.':'Công bố bộ câu hỏi đã kiểm tra cho người học?'))void action({op:b.status==='published'?'withdraw':'publish',id:b.id});}}>{b.status==='published'?'Thu hồi':'Công bố bộ đề'}</button></article>)}</section>;
}
