'use client';
import {useState} from 'react';
type Limits={uploads_paused:boolean;exams_paused:boolean;exam_month_limit:number|null;pdf_file_mb:number|null;pdf_storage_mb:number|null};
type Status={settings:Limits;pdfBytes:number;examStarts:number;month:string};
async function request(payload:unknown){const r=await fetch('/api/hoc-tap',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(payload)});const d=await r.json();if(!r.ok)throw Error(d.error||'Chưa lưu được cấu hình.');return d as Status;}
export default function UsageControls(){
 const [data,setData]=useState<Status|null>(null),[draft,setDraft]=useState<Limits|null>(null),[busy,setBusy]=useState(false),[message,setMessage]=useState('');
 async function load(){setBusy(true);setMessage('');try{const d=await request({op:'usageGet'});setData(d);setDraft(d.settings);}catch(e){setMessage((e as Error).message);}finally{setBusy(false);}}
 async function save(e:React.FormEvent){e.preventDefault();if(!draft)return;setBusy(true);setMessage('');try{const d=await request({...draft,op:'usageSet'});setData(d);setDraft(d.settings);setMessage('Đã lưu giới hạn sử dụng.');}catch(e){setMessage((e as Error).message);}finally{setBusy(false);}}
 const options:[keyof Pick<Limits,'exam_month_limit'|'pdf_file_mb'|'pdf_storage_mb'>,string,number][]=[['exam_month_limit','Lượt mở bài thi mỗi tháng',1000],['pdf_file_mb','Dung lượng tối đa mỗi PDF (MB)',20],['pdf_storage_mb','Tổng dung lượng PDF cấp cho R2 (MB)',8192]];
 return <details style={{margin:'20px 0',padding:16,border:'1px solid #ccdce2',borderRadius:10}}><summary style={{fontWeight:700,cursor:'pointer'}}>Giới hạn sử dụng · Upload và thi thử</summary><p style={{fontSize:13}}>Auto: website không đặt thêm hạn mức. Hạn mức của nhà cung cấp và giới hạn kỹ thuật PDF 20 MB/ảnh nén 1 MB vẫn áp dụng.</p><button type="button" disabled={busy} onClick={()=>void load()}>Tải cấu hình hiện tại</button>{data&&draft&&<form onSubmit={save}><p>Tháng {data.month.slice(0,7)}: {data.examStarts.toLocaleString('vi-VN')} lượt mở bài · PDF cấp cho R2: {(data.pdfBytes/1048576).toFixed(2)} MB.</p><fieldset disabled={busy}><label style={{display:'flex',gap:10,alignItems:'center'}}><input style={{width:'auto'}} type="checkbox" checked={draft.uploads_paused} onChange={e=>setDraft({...draft,uploads_paused:e.target.checked})}/>Tạm ngừng tải tệp lên (PDF, avatar, ảnh hoạt động và khen thưởng)</label><label style={{display:'flex',gap:10,alignItems:'center'}}><input style={{width:'auto'}} type="checkbox" checked={draft.exams_paused} onChange={e=>setDraft({...draft,exams_paused:e.target.checked})}/>Tạm ngừng mở bài thi mới</label><p style={{fontSize:13}}>Bài đang làm vẫn lưu và nộp được. Tài liệu đã có vẫn xem được. Bấm Lưu để áp dụng.</p>{options.map(([key,label,value])=><label key={key}>{label}<select value={draft[key]===null?'auto':'manual'} onChange={e=>setDraft({...draft,[key]:e.target.value==='auto'?null:value})}><option value="auto">Auto · Không đặt hạn mức</option><option value="manual">Đặt mức riêng</option></select>{draft[key]!==null&&<input type="number" required min={1} max={key==='pdf_file_mb'?20:2147483647} step={1} value={draft[key]!} onChange={e=>setDraft({...draft,[key]:Number(e.target.value)})}/>}</label>)}<button type="submit">{busy?'Đang lưu…':'Lưu giới hạn'}</button></fieldset><p style={{fontSize:12}}>Bộ đếm lượt thi theo tháng dương lịch, giờ Việt Nam; không phải chu kỳ hóa đơn Supabase. PDF cấp cho R2 bao gồm lượt tải đang chờ hoặc tải dở. Có thể dọn lượt tải dở trong mục Kho PDF. Đây là giới hạn hoạt động của website, không phải khóa chi phí của Cloudflare/Supabase.</p></form>}{message&&<p role="status">{message}</p>}</details>;
}
