'use client';
import {useCallback,useEffect,useRef,useState} from 'react';
import Link from 'next/link';
import {datePeriod,monthPeriod,yearPeriod,vnInput,vnStamp} from '../../../lib/office-calendar';
import s from './calendar.module.css';
type Person={id:string;name:string;username?:string;role?:string};
type Category={id:string;name:string};
type Task={id:string;content:string;category_id:string;category_name:string;received_at:string;due_at:string;lead_id:string;lead_name:string;helpers:Person[];version:number;completed_at:string|null;result_text:string;assigned:boolean;status:'done'|'overdue'|'soon'|'active'};
type Update={id:string;actor_name:string;kind:string;body:string;created_at:string;file_name:string|null;file_bytes:number|null};
type Data={me:Person|null;rows:Task[];people:Person[];categories:Category[];groups:(Category&{count:number})[];counts:{total:number;completed:number;overdue:number;soon:number;mine:number};total:number;serverTime:string};
const labels={done:'Đã hoàn thành',overdue:'Quá hạn',soon:'Sắp đến hạn',active:'Đang thực hiện'};
const kinds:Record<string,string>={created:'Giao nhiệm vụ',assigned:'Điều chỉnh phân công',progress:'Cập nhật kết quả',completed:'Chốt hoàn thành',reopened:'Mở lại nhiệm vụ'};
const endpoint='/api/lich-ctd-ctct';
const initial:Data={me:null,rows:[],people:[],categories:[],groups:[],counts:{total:0,completed:0,overdue:0,soon:0,mine:0},total:0,serverTime:''};
async function get(url:string){const r=await fetch(url,{cache:'no-store'});const d=await r.json();if(r.status===401)return {...initial};if(!r.ok)throw Error(d.error||'Không kết nối được lịch.');return d;}
export default function OfficeCalendar(){
 const [data,setData]=useState<Data>(initial),[loaded,setLoaded]=useState(false),[tab,setTab]=useState<'all'|'mine'|'summary'>('all'),[page,setPage]=useState(1),[error,setError]=useState(''),[notice,setNotice]=useState(''),[syncing,setSyncing]=useState(false),[busy,setBusy]=useState(false);
 const [year,setYear]=useState(2026),[month,setMonth]=useState(1),[period,setPeriod]=useState('month'),[category,setCategory]=useState('');
 const [editor,setEditor]=useState<Task|'new'|null>(null),[detail,setDetail]=useState<Task|null>(null),[updates,setUpdates]=useState<Update[]>([]),[historyPage,setHistoryPage]=useState(1),[historyTotal,setHistoryTotal]=useState(0),[historyLoading,setHistoryLoading]=useState(false),[modalError,setModalError]=useState('');
 const [lead,setLead]=useState(''),[helpers,setHelpers]=useState<string[]>([]),[showCategories,setShowCategories]=useState(false),[showExport,setShowExport]=useState(false),[exporting,setExporting]=useState(false);
 const dialog=useRef<HTMLDialogElement>(null),sequence=useRef(0),historySeq=useRef(0),mounted=useRef(true);
 useEffect(()=>{mounted.current=true;const now=vnInput(new Date().toISOString());setYear(Number(now.slice(0,4)));setMonth(Number(now.slice(5,7)));return()=>{mounted.current=false;sequence.current++};},[]);
 const refresh=useCallback(async()=>{const n=++sequence.current;setSyncing(true);try{const q=new URLSearchParams({tab,page:String(page)});if(tab==='summary'){const range=period==='month'?monthPeriod(year,month):yearPeriod(year);q.set('from',range.from);q.set('until',range.until);if(category)q.set('category',category);}const d=await get(endpoint+'?'+q);if(n!==sequence.current||!mounted.current)return;setData(d);setLoaded(true);setError('');if(d.me&&page>1&&d.rows.length===0)setPage(Math.max(1,Math.ceil(d.total/20)));}catch(e){if(n===sequence.current&&mounted.current){setError((e as Error).message);setLoaded(true);}}finally{if(n===sequence.current&&mounted.current)setSyncing(false);}},[tab,page,period,year,month,category]);
 useEffect(()=>{refresh();},[refresh]);
 useEffect(()=>{const run=()=>{if(!document.hidden&&!editor&&!detail&&!busy&&!showCategories)refresh();};const t=setInterval(run,30000);document.addEventListener('visibilitychange',run);window.addEventListener('online',run);return()=>{clearInterval(t);document.removeEventListener('visibilitychange',run);window.removeEventListener('online',run);};},[refresh,editor,detail,busy,showCategories]);
 useEffect(()=>{if(editor||detail){if(!dialog.current?.open)dialog.current?.showModal();}else dialog.current?.close();},[editor,detail]);
 const admin=data.me?.role==='admin';
 function switchTab(next:typeof tab){setTab(next);setPage(1);setNotice('');}
 function close(){if(busy)return;historySeq.current++;setEditor(null);setDetail(null);setModalError('');}
 async function submit(payload:Record<string,unknown>,file?:File){const form=new FormData();form.set('payload',JSON.stringify(payload));if(file?.size)form.set('file',file);const r=await fetch(endpoint,{method:'POST',body:form});const d=await r.json();if(!r.ok)throw Error(d.error||'Không lưu được.');return d;}
 async function history(t:Task,p=1){const n=++historySeq.current;setHistoryLoading(true);setModalError('');try{const d=await get(`${endpoint}?op=detail&id=${t.id}&page=${p}`);if(!d.task)throw Error('Phiên đăng nhập đã hết hạn.');if(n!==historySeq.current)return;setUpdates(d.updates);setHistoryTotal(d.total);setHistoryPage(p);if(d.task.version!==t.version)setModalError('Nhiệm vụ có cập nhật mới. Hãy đóng khung và bấm Cập nhật trước khi ghi kết quả.');}catch(e){if(n===historySeq.current)setModalError((e as Error).message);}finally{if(n===historySeq.current)setHistoryLoading(false);}}
 function openDetail(t:Task){setDetail(t);setEditor(null);setUpdates([]);setHistoryTotal(0);history(t);}
 function edit(t:Task|'new'){setDetail(null);setEditor(t);setModalError('');setLead(t==='new'?'':t.lead_id);setHelpers(t==='new'?[]:t.helpers.map(x=>x.id));}
 async function saveTask(e:React.FormEvent<HTMLFormElement>){e.preventDefault();const f=new FormData(e.currentTarget);setBusy(true);setModalError('');try{await submit({op:editor==='new'?'create':'edit',...(editor&&editor!=='new'?{id:editor.id,version:editor.version}:{}),content:f.get('content'),category_id:f.get('category_id'),lead_id:lead,helpers,received_at:f.get('received_at')+':00+07:00',due_at:f.get('due_at')+':00+07:00'});setEditor(null);setNotice('Đã lưu nhiệm vụ và phân công.');await refresh();}catch(e){setModalError((e as Error).message);}finally{setBusy(false);}}
 async function report(e:React.FormEvent<HTMLFormElement>){e.preventDefault();if(!detail)return;const f=new FormData(e.currentTarget),op=(e.nativeEvent as SubmitEvent).submitter?.getAttribute('value')||'progress';const file=f.get('file');if(file instanceof File&&file.size>3145728){setModalError('Tệp tối đa 3 MB. Có thể lưu nội dung kết quả không kèm tệp.');return;}setBusy(true);setModalError('');try{await submit({op:op==='reopen'?'reopen':'report',id:detail.id,version:detail.version,body:f.get('body'),complete:op==='complete'},file instanceof File?file:undefined);setDetail(null);setNotice(op==='complete'?'Đã hoàn thành. Nhiệm vụ được lưu ở Tổng thể và Tổng hợp kết quả.':'Đã lưu cập nhật.');await refresh();}catch(e){setModalError((e as Error).message);}finally{setBusy(false);}}
 async function addCategory(e:React.FormEvent<HTMLFormElement>){e.preventDefault();const el=e.currentTarget;setBusy(true);setError('');try{await submit({op:'category',name:new FormData(el).get('name')});el.reset();setNotice('Đã thêm loại nhiệm vụ.');await refresh();}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 async function exportList(e:React.FormEvent<HTMLFormElement>){e.preventDefault();setExporting(true);setError('');try{const f=new FormData(e.currentTarget),from=String(f.get('from')),to=String(f.get('to')),field=String(f.get('date_field'));const q=new URLSearchParams({op:'export',date_field:field,...datePeriod(from,to)});const d=await get(endpoint+'?'+q);if(!d.me)throw Error('Vui lòng đăng nhập lại.');if(!d.rows.length)throw Error('Không có nhiệm vụ trong khoảng thời gian đã chọn.');const ExcelJS=(await import('exceljs')).default;const wb=new ExcelJS.Workbook();const ws=wb.addWorksheet('Lịch CTĐ CTCT');ws.columns=[{header:'Thời gian nhận',key:'received_at',width:22},{header:'Loại nhiệm vụ',key:'category_name',width:30},{header:'Nội dung',key:'content',width:55},{header:'Người phụ trách',key:'lead_name',width:25},{header:'Người hỗ trợ',key:'helper_names',width:28},{header:'Hạn thực hiện',key:'due_at',width:22},{header:'Trạng thái',key:'status',width:20},{header:'Kết quả',key:'result_text',width:55},{header:'Hoàn thành lúc',key:'completed_at',width:22}];for(const r of d.rows){const row=ws.addRow({...r,received_at:vnStamp(r.received_at),due_at:vnStamp(r.due_at),completed_at:vnStamp(r.completed_at)});row.alignment={vertical:'top',wrapText:true};if(r.completed_at)row.fill={type:'pattern',pattern:'solid',fgColor:{argb:'FFE5F2E9'}};}ws.getRow(1).font={bold:true,color:{argb:'FFFFFFFF'}};ws.getRow(1).fill={type:'pattern',pattern:'solid',fgColor:{argb:'FF173F50'}};ws.views=[{state:'frozen',ySplit:1}];ws.autoFilter='A1:I1';const meta=wb.addWorksheet('Phạm vi');meta.addRows([['LỊCH CTĐ, CTCT VĂN PHÒNG'],['Lọc theo',field==='received'?'Ngày nhận nhiệm vụ':'Ngày hoàn thành'],['Từ ngày',from],['Đến hết ngày',to],['Số nhiệm vụ',d.rows.length],['Đồng bộ lúc',vnStamp(d.serverTime)]]);meta.getColumn(1).width=28;meta.getColumn(2).width=35;const bytes=await wb.xlsx.writeBuffer();const url=URL.createObjectURL(new Blob([bytes as BlobPart],{type:'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet'}));const a=document.createElement('a');a.href=url;a.download=`lich-ctd-ctct-${from}-${to}.xlsx`;a.click();setTimeout(()=>URL.revokeObjectURL(url),10000);setNotice(`Đã xuất ${d.rows.length} nhiệm vụ, gồm tất cả các trang trong khoảng ngày đã chọn.`);}catch(e){setError((e as Error).message);}finally{setExporting(false);}}
 const canReport=detail&&!detail.completed_at&&(admin||(tab==='mine'&&detail.assigned));
 return <main className={s.page}><nav className={s.top}><Link href="/">← Trang chủ</Link><Link href="/cong-cu/bao-ban-ngay">Báo cáo ngày →</Link></nav>
 <header className={s.hero}><div><p className={s.partyTitle}>Công tác Đảng,<br/>Công tác Chính trị</p><p className={s.eyebrow}>VĂN PHÒNG TỔNG CÔNG TY</p><h1>Lịch CTĐ, CTCT</h1><p className={s.tagline}>PHƯƠNG CHÂM 6 RÕ · Rõ người · Rõ việc · Rõ trách nhiệm · Rõ thẩm quyền · Rõ thời gian · Rõ kết quả</p></div><div className={s.snpBrand}><img src="/logo-snp.webp" width="104" height="120" alt="Logo SNP — Tổng công ty Tân Cảng Sài Gòn"/><span>TÂN CẢNG SÀI GÒN</span></div><div className={s.heroBottom}><span className={syncing?s.syncing:s.sync}><i/>{syncing?'Đang đồng bộ…':data.serverTime?'Đồng bộ '+vnStamp(data.serverTime):'Chưa đồng bộ'}</span><span>Tự cập nhật 30 giây khi xem lịch · Giờ Việt Nam</span></div></header><p className={s.purpose}>Số hóa công tác Đảng, công tác chính trị tại Văn phòng Tổng công ty, góp phần cụ thể hóa các chỉ đạo, nghị quyết về cải cách hành chính và chuyển đổi số. Công cụ kết nối giao nhiệm vụ, phối hợp thực hiện, theo dõi tiến độ và lưu kết quả trên cùng một hệ thống; nâng cao trách nhiệm cá nhân, giảm tổng hợp thủ công và phục vụ công tác chỉ đạo, điều hành.</p>
 {error&&<div role="alert" className={s.error}>{error} <button onClick={refresh}>Thử lại</button></div>}{notice&&<p role="status" className={s.notice}>{notice}</p>}
 {!loaded?<section className={s.empty}>Đang tải lịch công tác…</section>:!data.me?<section className={s.empty}><h2>Đăng nhập để theo dõi lịch công tác</h2><p>Sử dụng tài khoản học tập hiện có để xem nhiệm vụ và cập nhật phần việc được giao.</p><Link className={s.primary} href="/dang-nhap?next=/cong-cu/lich-ctd-ctct">Đăng nhập →</Link></section>:<>
 <section className={s.stats} aria-label="Tổng quan"><div><span>Tổng nhiệm vụ</span><b>{data.counts.total}</b></div><div><span>Đã hoàn thành</span><b>{data.counts.completed}</b></div><div className={s.statDanger}><span>Quá hạn</span><b>{data.counts.overdue}</b></div><div><span>Đến hạn trong 2 ngày</span><b>{data.counts.soon}</b></div></section>
 <div className={s.toolbar}><div><strong>{data.me.name}</strong><small>{admin?'Quản trị viên · Giao việc và chốt kết quả':'Theo dõi công việc của Văn phòng'}</small></div><div className={s.actions}><button disabled={syncing} onClick={refresh}>↻ Cập nhật</button><button onClick={()=>setShowExport(!showExport)}>↓ Xuất Excel</button>{admin&&<><button onClick={()=>setShowCategories(!showCategories)}>Loại nhiệm vụ</button><button className={s.primary} onClick={()=>edit('new')}>＋ Giao nhiệm vụ</button></>}</div></div>
 {showCategories&&admin&&<section className={s.panel}><h2>Loại nhiệm vụ</h2><div className={s.categoryList}>{data.categories.map(c=><span key={c.id}>{c.name}</span>)}</div><form className={s.inlineForm} onSubmit={addCategory}><label>Tên loại mới<input name="name" required maxLength={100} placeholder="Ví dụ: Kiểm tra, giám sát"/></label><button disabled={busy}>Thêm loại</button></form></section>}
 {showExport&&<section className={s.panel}><h2>Xuất danh sách theo khoảng thời gian</h2><form className={s.inlineForm} onSubmit={exportList}><label>Lọc theo<select name="date_field" defaultValue={tab==='summary'?'completed':'received'}><option value="received">Ngày nhận nhiệm vụ</option><option value="completed">Ngày hoàn thành</option></select></label><label>Từ ngày<input name="from" type="date" defaultValue={`${year}-01-01`} required/></label><label>Đến hết ngày<input name="to" type="date" defaultValue={vnInput(new Date().toISOString()).slice(0,10)} required/></label><button disabled={exporting}>{exporting?'Đang xuất…':'Tải Excel'}</button></form><p className={s.sub}>Xuất tất cả nhiệm vụ trong khoảng ngày, không chỉ trang đang xem. Tối đa 5.000 nhiệm vụ mỗi lần; tệp đính kèm mở riêng.</p></section>}
 <div className={s.tabs} role="tablist" aria-label="Chế độ xem lịch">{([['all','Tổng thể'],['mine',`Nhiệm vụ của tôi (${data.counts.mine})`],['summary','Tổng hợp kết quả']] as const).map(([v,label])=><button id={`tab-${v}`} aria-controls="calendar-panel" role="tab" aria-selected={tab===v} key={v} onClick={()=>switchTab(v)}>{label}</button>)}</div>
 <section id="calendar-panel" role="tabpanel" aria-labelledby={`tab-${tab}`}>
 {tab==='summary'?<section className={s.summary}><div className={s.inlineForm}><label>Kỳ tổng hợp<select value={period} onChange={e=>{setPeriod(e.target.value);setPage(1)}}><option value="month">Kỳ tháng · chốt ngày 25</option><option value="year">Cả năm</option></select></label>{period==='month'&&<label>Tháng chốt<select value={month} onChange={e=>{setMonth(Number(e.target.value));setPage(1)}}>{Array.from({length:12},(_,i)=><option value={i+1} key={i}>{i+1}</option>)}</select></label>}<label>Năm<select value={year} onChange={e=>{setYear(Number(e.target.value));setPage(1)}}>{Array.from({length:31},(_,i)=><option key={i} value={2020+i}>{2020+i}</option>)}</select></label></div><p>{period==='month'?`Kỳ ${month}/${year}: từ ngày 26 tháng trước đến hết ngày 25 tháng này.`:`Từ 01/01/${year} đến hết 31/12/${year}.`} Tính theo ngày chốt hoàn thành.</p><div className={s.groups}><button aria-pressed={!category} onClick={()=>{setCategory('');setPage(1)}}><span>Tất cả loại</span><b>{data.groups.reduce((n,g)=>n+g.count,0)}</b></button>{data.groups.map(g=><button key={g.id} aria-pressed={category===g.id} onClick={()=>{setCategory(g.id);setPage(1)}}><span>{g.name}</span><b>{g.count}</b></button>)}</div></section>:<div className={s.legend}><span>● Xanh: hoàn thành</span><span>● Trắng: đang thực hiện</span><span>● Đỏ: gần hạn / quá hạn, ưu tiên trên cùng</span></div>}
 {tab==='mine'&&<p className={s.sub}>Chỉ hiện nhiệm vụ đang được phân công chính hoặc hỗ trợ. Khi người phụ trách chính hoặc admin chốt hoàn thành, nhiệm vụ tự rời danh sách này.</p>}
 <div className={s.tableWrap} aria-busy={syncing}><table className={s.table}><caption className={s.sr}>Lịch công tác Đảng, công tác chính trị</caption><thead><tr><th>Thời gian nhận</th><th>Loại nhiệm vụ</th><th>Nội dung</th><th>Người phụ trách</th><th>Người hỗ trợ</th><th>Hạn thực hiện</th><th>Kết quả</th></tr></thead><tbody>{data.rows.map(t=><tr key={t.id} className={s[t.status]}><td>{vnStamp(t.received_at)}</td><td><span className={s.category}>{t.category_name}</span></td><td><strong className={s.taskText}>{t.content}</strong><div className={s.rowActions}><button onClick={()=>openDetail(t)}>{tab==='mine'?'Cập nhật kết quả':'Chi tiết'}</button>{admin&&!t.completed_at&&<button onClick={()=>edit(t)}>Sửa phân công</button>}</div></td><td><b>{t.lead_name}</b>{tab==='mine'&&t.lead_id===data.me?.id&&<small>Phụ trách chính</small>}</td><td>{t.helpers.length?t.helpers.map(h=><span className={s.helper} key={h.id}>{h.name}</span>):'—'}</td><td><b>{vnStamp(t.due_at)}</b>{t.status==='overdue'&&<small>Đã qua hạn</small>}{t.status==='soon'&&<small>Cần ưu tiên</small>}</td><td><span className={s.badge}>{labels[t.status]}</span>{t.result_text&&<p className={s.result}>{t.result_text}</p>}{t.completed_at&&<small>{vnStamp(t.completed_at)}</small>}</td></tr>)}</tbody></table>{!data.rows.length&&<div className={s.empty}><h3>{tab==='mine'?'Không còn nhiệm vụ cần thực hiện':tab==='summary'?'Chưa có kết quả trong kỳ này':'Chưa có nhiệm vụ'}</h3><p>{tab==='mine'?'Các nhiệm vụ đã hoàn thành vẫn được lưu ở Tổng thể và Tổng hợp kết quả.':'Nội dung sẽ hiển thị khi được quản trị viên cập nhật.'}</p></div>}</div>
 <div className={s.pagination}><span>{data.total} nhiệm vụ · Trang {page}/{Math.max(1,Math.ceil(data.total/20))}</span><div><button disabled={page===1||syncing} onClick={()=>setPage(page-1)}>← Trước</button><button disabled={page*20>=data.total||syncing} onClick={()=>setPage(page+1)}>Sau →</button></div></div></section></>}
 <dialog ref={dialog} className={s.dialog} onCancel={e=>{e.preventDefault();close()}} onClose={()=>{if(!busy){setEditor(null);setDetail(null)}}}><header><h2>{editor?editor==='new'?'Giao nhiệm vụ mới':'Điều chỉnh phân công':'Chi tiết nhiệm vụ'}</h2><button type="button" disabled={busy} onClick={close} aria-label="Đóng">✕</button></header>{modalError&&<p className={s.error} role="alert">{modalError}</p>}
 {editor&&<form onSubmit={saveTask} key={editor==='new'?'new':editor.id}><fieldset disabled={busy}><label>Nội dung nhiệm vụ *<textarea name="content" maxLength={4000} required rows={4} defaultValue={editor==='new'?'':editor.content}/></label><label>Loại nhiệm vụ *<select name="category_id" required defaultValue={editor==='new'?'':editor.category_id}><option value="" disabled>Chọn loại</option>{data.categories.map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select></label><div className={s.two}><label>Thời gian nhận (giờ Việt Nam) *<input name="received_at" type="datetime-local" required defaultValue={editor==='new'?vnInput(new Date().toISOString()):vnInput(editor.received_at)}/></label><label>Hạn phải thực hiện (giờ Việt Nam) *<input name="due_at" type="datetime-local" required defaultValue={editor==='new'?'':vnInput(editor.due_at)}/></label></div><label>Người phụ trách chính *<select required value={lead} onChange={e=>{setLead(e.target.value);setHelpers(helpers.filter(id=>id!==e.target.value))}}><option value="">Chọn tài khoản</option>{data.people.map(p=><option key={p.id} value={p.id}>{p.name} · {p.username}</option>)}</select></label><fieldset className={s.checklist}><legend>Người hỗ trợ (có thể chọn nhiều)</legend>{data.people.filter(p=>p.id!==lead).map(p=><label key={p.id}><input type="checkbox" checked={helpers.includes(p.id)} onChange={e=>setHelpers(e.target.checked?[...helpers,p.id]:helpers.filter(id=>id!==p.id))}/>{p.name} <small>({p.username})</small></label>)}</fieldset><button className={s.primary} disabled={busy}>{busy?'Đang lưu…':'Lưu nhiệm vụ'}</button></fieldset></form>}
 {detail&&<><div className={s.detail}><span className={s.category}>{detail.category_name}</span><h3>{detail.content}</h3><p><b>Phụ trách:</b> {detail.lead_name} · <b>Hạn:</b> {vnStamp(detail.due_at)}</p><span className={s.badge}>{labels[detail.status]}</span></div>{(canReport||(admin&&detail.completed_at))&&<form className={s.report} onSubmit={report}><fieldset disabled={busy}><h3>{detail.completed_at?'Mở lại nhiệm vụ':'Cập nhật kết quả'}</h3><label>{detail.completed_at?'Lý do mở lại *':'Nội dung kết quả / tên kế hoạch *'}<textarea name="body" required maxLength={4000} rows={4} placeholder="Ghi rõ nội dung đã thực hiện và kết quả đạt được…"/></label>{!detail.completed_at&&<label>Tệp kết quả (không bắt buộc)<input type="file" name="file" accept=".pdf,.doc,.docx"/><small>Word hoặc PDF · tối đa 3 MB/tệp · mỗi cập nhật có thể kèm 1 tệp.</small></label>}<div className={s.actions}>{detail.completed_at?<button value="reopen">Mở lại và giao tiếp</button>:<><button value="progress">Lưu tiến độ</button>{(admin||detail.lead_id===data.me?.id)&&<button className={s.primary} value="complete">✓ Chốt hoàn thành</button>}</>}</div><p className={s.sub}>{busy?'Đang lưu, vui lòng giữ nguyên cửa sổ…':'Nội dung bắt buộc kể cả khi có tệp. Chốt hoàn thành sẽ kết thúc nhiệm vụ của cả nhóm.'}</p></fieldset></form>}{!canReport&&!detail.completed_at&&!admin&&<p className={s.sub}>{detail.assigned?'Vào tab Nhiệm vụ của tôi để cập nhật kết quả.':'Bạn đang xem nhiệm vụ được giao cho người khác.'}</p>}
 <section className={s.history}><h3>Lịch sử cập nhật</h3>{historyLoading?<p>Đang tải lịch sử…</p>:updates.map(u=><article key={u.id}><header><strong>{u.actor_name}</strong><time>{vnStamp(u.created_at)}</time></header><small>{kinds[u.kind]||u.kind}</small><p>{u.body}</p>{u.file_name&&<a href={`${endpoint}?op=file&id=${detail.id}&update_id=${u.id}`} target="_blank" rel="noopener noreferrer">↓ {u.file_name} ({Math.ceil((u.file_bytes||0)/1024)} KB)</a>}</article>)}<div className={s.pagination}><span>{historyTotal} cập nhật</span><button type="button" disabled={historyPage===1||historyLoading||busy} onClick={()=>history(detail,historyPage-1)}>Trước</button><button type="button" disabled={historyPage*20>=historyTotal||historyLoading||busy} onClick={()=>history(detail,historyPage+1)}>Sau</button></div></section></>}
 </dialog><footer className={s.footer}>LỊCH CTĐ, CTCT VĂN PHÒNG · Kết quả được lưu theo từng cập nhật. Chỉ tải tệp khi chọn mở tệp.</footer></main>;
}
